/** Kids' corner content for the Learning module. */

export const ARABIC_ALPHABET: { letter: string; name: string; sound: string }[] = [
  { letter: 'ا', name: 'Alif', sound: 'a' },
  { letter: 'ب', name: 'Baa', sound: 'b' },
  { letter: 'ت', name: 'Taa', sound: 't' },
  { letter: 'ث', name: 'Thaa', sound: 'th (as in “think”)' },
  { letter: 'ج', name: 'Jeem', sound: 'j' },
  { letter: 'ح', name: 'Haa', sound: 'h (from the throat)' },
  { letter: 'خ', name: 'Khaa', sound: 'kh' },
  { letter: 'د', name: 'Daal', sound: 'd' },
  { letter: 'ذ', name: 'Dhaal', sound: 'th (as in “this”)' },
  { letter: 'ر', name: 'Raa', sound: 'r' },
  { letter: 'ز', name: 'Zaay', sound: 'z' },
  { letter: 'س', name: 'Seen', sound: 's' },
  { letter: 'ش', name: 'Sheen', sound: 'sh' },
  { letter: 'ص', name: 'Saad', sound: 's (heavy)' },
  { letter: 'ض', name: 'Daad', sound: 'd (heavy)' },
  { letter: 'ط', name: 'Taa', sound: 't (heavy)' },
  { letter: 'ظ', name: 'Dhaa', sound: 'dh (heavy)' },
  { letter: 'ع', name: 'ʿAyn', sound: 'ʿ (from the throat)' },
  { letter: 'غ', name: 'Ghayn', sound: 'gh' },
  { letter: 'ف', name: 'Faa', sound: 'f' },
  { letter: 'ق', name: 'Qaaf', sound: 'q (deep k)' },
  { letter: 'ك', name: 'Kaaf', sound: 'k' },
  { letter: 'ل', name: 'Laam', sound: 'l' },
  { letter: 'م', name: 'Meem', sound: 'm' },
  { letter: 'ن', name: 'Noon', sound: 'n' },
  { letter: 'ه', name: 'Haa', sound: 'h' },
  { letter: 'و', name: 'Waaw', sound: 'w / oo' },
  { letter: 'ي', name: 'Yaa', sound: 'y / ee' },
];

/** The commonly recited list of 99 Names (based on the narration in Jami‘ at-Tirmidhi). */
export const NAMES_OF_ALLAH: { arabic: string; name: string; meaning: string }[] = [
  { arabic: 'الرَّحْمَٰنُ', name: 'Ar-Rahman', meaning: 'The Most Gracious' },
  { arabic: 'الرَّحِيمُ', name: 'Ar-Rahim', meaning: 'The Most Merciful' },
  { arabic: 'الْمَلِكُ', name: 'Al-Malik', meaning: 'The King' },
  { arabic: 'الْقُدُّوسُ', name: 'Al-Quddus', meaning: 'The Most Holy' },
  { arabic: 'السَّلَامُ', name: 'As-Salam', meaning: 'The Source of Peace' },
  { arabic: 'الْمُؤْمِنُ', name: "Al-Mu'min", meaning: 'The Giver of Faith and Security' },
  { arabic: 'الْمُهَيْمِنُ', name: 'Al-Muhaymin', meaning: 'The Guardian' },
  { arabic: 'الْعَزِيزُ', name: 'Al-Aziz', meaning: 'The Almighty' },
  { arabic: 'الْجَبَّارُ', name: 'Al-Jabbar', meaning: 'The Compeller' },
  { arabic: 'الْمُتَكَبِّرُ', name: 'Al-Mutakabbir', meaning: 'The Supreme in Greatness' },
  { arabic: 'الْخَالِقُ', name: 'Al-Khaliq', meaning: 'The Creator' },
  { arabic: 'الْبَارِئُ', name: "Al-Bari'", meaning: 'The Maker' },
  { arabic: 'الْمُصَوِّرُ', name: 'Al-Musawwir', meaning: 'The Fashioner of Forms' },
  { arabic: 'الْغَفَّارُ', name: 'Al-Ghaffar', meaning: 'The Ever-Forgiving' },
  { arabic: 'الْقَهَّارُ', name: 'Al-Qahhar', meaning: 'The Subduer' },
  { arabic: 'الْوَهَّابُ', name: 'Al-Wahhab', meaning: 'The Bestower' },
  { arabic: 'الرَّزَّاقُ', name: 'Ar-Razzaq', meaning: 'The Provider' },
  { arabic: 'الْفَتَّاحُ', name: 'Al-Fattah', meaning: 'The Opener' },
  { arabic: 'الْعَلِيمُ', name: 'Al-Alim', meaning: 'The All-Knowing' },
  { arabic: 'الْقَابِضُ', name: 'Al-Qabid', meaning: 'The Withholder' },
  { arabic: 'الْبَاسِطُ', name: 'Al-Basit', meaning: 'The Extender' },
  { arabic: 'الْخَافِضُ', name: 'Al-Khafid', meaning: 'The Abaser' },
  { arabic: 'الرَّافِعُ', name: "Ar-Rafi'", meaning: 'The Exalter' },
  { arabic: 'الْمُعِزُّ', name: "Al-Mu'izz", meaning: 'The Giver of Honour' },
  { arabic: 'الْمُذِلُّ', name: 'Al-Mudhill', meaning: 'The Giver of Dishonour' },
  { arabic: 'السَّمِيعُ', name: "As-Sami'", meaning: 'The All-Hearing' },
  { arabic: 'الْبَصِيرُ', name: 'Al-Basir', meaning: 'The All-Seeing' },
  { arabic: 'الْحَكَمُ', name: 'Al-Hakam', meaning: 'The Judge' },
  { arabic: 'الْعَدْلُ', name: 'Al-Adl', meaning: 'The Utterly Just' },
  { arabic: 'اللَّطِيفُ', name: 'Al-Latif', meaning: 'The Subtle, the Most Kind' },
  { arabic: 'الْخَبِيرُ', name: 'Al-Khabir', meaning: 'The All-Aware' },
  { arabic: 'الْحَلِيمُ', name: 'Al-Halim', meaning: 'The Forbearing' },
  { arabic: 'الْعَظِيمُ', name: 'Al-Azim', meaning: 'The Magnificent' },
  { arabic: 'الْغَفُورُ', name: 'Al-Ghafur', meaning: 'The All-Forgiving' },
  { arabic: 'الشَّكُورُ', name: 'Ash-Shakur', meaning: 'The Most Appreciative' },
  { arabic: 'الْعَلِيُّ', name: 'Al-Aliyy', meaning: 'The Most High' },
  { arabic: 'الْكَبِيرُ', name: 'Al-Kabir', meaning: 'The Most Great' },
  { arabic: 'الْحَفِيظُ', name: 'Al-Hafiz', meaning: 'The Preserver' },
  { arabic: 'الْمُقِيتُ', name: 'Al-Muqit', meaning: 'The Sustainer' },
  { arabic: 'الْحَسِيبُ', name: 'Al-Hasib', meaning: 'The Reckoner' },
  { arabic: 'الْجَلِيلُ', name: 'Al-Jalil', meaning: 'The Majestic' },
  { arabic: 'الْكَرِيمُ', name: 'Al-Karim', meaning: 'The Most Generous' },
  { arabic: 'الرَّقِيبُ', name: 'Ar-Raqib', meaning: 'The Watchful' },
  { arabic: 'الْمُجِيبُ', name: 'Al-Mujib', meaning: 'The Responsive' },
  { arabic: 'الْوَاسِعُ', name: "Al-Wasi'", meaning: 'The All-Encompassing' },
  { arabic: 'الْحَكِيمُ', name: 'Al-Hakim', meaning: 'The All-Wise' },
  { arabic: 'الْوَدُودُ', name: 'Al-Wadud', meaning: 'The Most Loving' },
  { arabic: 'الْمَجِيدُ', name: 'Al-Majid', meaning: 'The Most Glorious' },
  { arabic: 'الْبَاعِثُ', name: "Al-Ba'ith", meaning: 'The Resurrector' },
  { arabic: 'الشَّهِيدُ', name: 'Ash-Shahid', meaning: 'The Witness' },
  { arabic: 'الْحَقُّ', name: 'Al-Haqq', meaning: 'The Truth' },
  { arabic: 'الْوَكِيلُ', name: 'Al-Wakil', meaning: 'The Trustee' },
  { arabic: 'الْقَوِيُّ', name: 'Al-Qawiyy', meaning: 'The All-Strong' },
  { arabic: 'الْمَتِينُ', name: 'Al-Matin', meaning: 'The Firm' },
  { arabic: 'الْوَلِيُّ', name: 'Al-Waliyy', meaning: 'The Protecting Friend' },
  { arabic: 'الْحَمِيدُ', name: 'Al-Hamid', meaning: 'The Praiseworthy' },
  { arabic: 'الْمُحْصِي', name: 'Al-Muhsi', meaning: 'The Accounter of All' },
  { arabic: 'الْمُبْدِئُ', name: "Al-Mubdi'", meaning: 'The Originator' },
  { arabic: 'الْمُعِيدُ', name: "Al-Mu'id", meaning: 'The Restorer' },
  { arabic: 'الْمُحْيِي', name: 'Al-Muhyi', meaning: 'The Giver of Life' },
  { arabic: 'الْمُمِيتُ', name: 'Al-Mumit', meaning: 'The Bringer of Death' },
  { arabic: 'الْحَيُّ', name: 'Al-Hayy', meaning: 'The Ever-Living' },
  { arabic: 'الْقَيُّومُ', name: 'Al-Qayyum', meaning: 'The Self-Sustaining' },
  { arabic: 'الْوَاجِدُ', name: 'Al-Wajid', meaning: 'The Finder' },
  { arabic: 'الْمَاجِدُ', name: 'Al-Majid', meaning: 'The Noble' },
  { arabic: 'الْوَاحِدُ', name: 'Al-Wahid', meaning: 'The One' },
  { arabic: 'الْأَحَدُ', name: 'Al-Ahad', meaning: 'The Unique' },
  { arabic: 'الصَّمَدُ', name: 'As-Samad', meaning: 'The Eternal Refuge' },
  { arabic: 'الْقَادِرُ', name: 'Al-Qadir', meaning: 'The All-Capable' },
  { arabic: 'الْمُقْتَدِرُ', name: 'Al-Muqtadir', meaning: 'The All-Powerful' },
  { arabic: 'الْمُقَدِّمُ', name: 'Al-Muqaddim', meaning: 'The Expediter' },
  { arabic: 'الْمُؤَخِّرُ', name: "Al-Mu'akhkhir", meaning: 'The Delayer' },
  { arabic: 'الْأَوَّلُ', name: 'Al-Awwal', meaning: 'The First' },
  { arabic: 'الْآخِرُ', name: 'Al-Akhir', meaning: 'The Last' },
  { arabic: 'الظَّاهِرُ', name: 'Az-Zahir', meaning: 'The Manifest' },
  { arabic: 'الْبَاطِنُ', name: 'Al-Batin', meaning: 'The Hidden' },
  { arabic: 'الْوَالِي', name: 'Al-Wali', meaning: 'The Governor' },
  { arabic: 'الْمُتَعَالِي', name: "Al-Muta'ali", meaning: 'The Self-Exalted' },
  { arabic: 'الْبَرُّ', name: 'Al-Barr', meaning: 'The Source of Goodness' },
  { arabic: 'التَّوَّابُ', name: 'At-Tawwab', meaning: 'The Accepter of Repentance' },
  { arabic: 'الْمُنْتَقِمُ', name: 'Al-Muntaqim', meaning: 'The Avenger' },
  { arabic: 'الْعَفُوُّ', name: "Al-'Afuww", meaning: 'The Pardoner' },
  { arabic: 'الرَّءُوفُ', name: "Ar-Ra'uf", meaning: 'The Most Kind' },
  { arabic: 'مَالِكُ الْمُلْكِ', name: 'Malik al-Mulk', meaning: 'Owner of All Sovereignty' },
  { arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', name: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Majesty and Generosity' },
  { arabic: 'الْمُقْسِطُ', name: 'Al-Muqsit', meaning: 'The Equitable' },
  { arabic: 'الْجَامِعُ', name: "Al-Jami'", meaning: 'The Gatherer' },
  { arabic: 'الْغَنِيُّ', name: 'Al-Ghaniyy', meaning: 'The Self-Sufficient' },
  { arabic: 'الْمُغْنِي', name: 'Al-Mughni', meaning: 'The Enricher' },
  { arabic: 'الْمَانِعُ', name: "Al-Mani'", meaning: 'The Preventer' },
  { arabic: 'الضَّارُّ', name: 'Ad-Darr', meaning: 'The Distresser' },
  { arabic: 'النَّافِعُ', name: "An-Nafi'", meaning: 'The Benefactor' },
  { arabic: 'النُّورُ', name: 'An-Nur', meaning: 'The Light' },
  { arabic: 'الْهَادِي', name: 'Al-Hadi', meaning: 'The Guide' },
  { arabic: 'الْبَدِيعُ', name: "Al-Badi'", meaning: 'The Incomparable Originator' },
  { arabic: 'الْبَاقِي', name: 'Al-Baqi', meaning: 'The Everlasting' },
  { arabic: 'الْوَارِثُ', name: 'Al-Warith', meaning: 'The Inheritor' },
  { arabic: 'الرَّشِيدُ', name: 'Ar-Rashid', meaning: 'The Guide to the Right Path' },
  { arabic: 'الصَّبُورُ', name: 'As-Sabur', meaning: 'The Most Patient' },
];

export const FIVE_PILLARS = [
  { name: 'Shahadah', meaning: 'Declaring that there is no god but Allah and Muhammad ﷺ is His Messenger' },
  { name: 'Salah', meaning: 'Praying five times a day' },
  { name: 'Zakah', meaning: 'Giving a share of your wealth to those in need' },
  { name: 'Sawm', meaning: 'Fasting in the month of Ramadan' },
  { name: 'Hajj', meaning: 'Pilgrimage to Makkah once in a lifetime, for those who are able' },
];

export const SIX_ARTICLES = [
  'Belief in Allah',
  'Belief in His angels',
  'Belief in His books',
  'Belief in His messengers',
  'Belief in the Last Day',
  'Belief in divine decree (al-Qadr)',
];

/** Short surahs children often learn first, with Quran.com numbers. */
export const STARTER_SURAHS: { number: number; name: string; ayahs: number }[] = [
  { number: 1, name: 'Al-Fatihah', ayahs: 7 },
  { number: 114, name: 'An-Nas', ayahs: 6 },
  { number: 113, name: 'Al-Falaq', ayahs: 5 },
  { number: 112, name: 'Al-Ikhlas', ayahs: 4 },
  { number: 111, name: 'Al-Masad', ayahs: 5 },
  { number: 110, name: 'An-Nasr', ayahs: 3 },
  { number: 109, name: 'Al-Kafirun', ayahs: 6 },
  { number: 108, name: 'Al-Kawthar', ayahs: 3 },
  { number: 107, name: "Al-Ma'un", ayahs: 7 },
  { number: 106, name: 'Quraysh', ayahs: 4 },
  { number: 105, name: 'Al-Fil', ayahs: 5 },
  { number: 104, name: 'Al-Humazah', ayahs: 9 },
  { number: 103, name: "Al-'Asr", ayahs: 3 },
  { number: 102, name: 'At-Takathur', ayahs: 8 },
];
