// Single-file copy of supabase/functions/companion/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/openai.ts ──
// Shared OpenAI helpers: retries short rate limits and turns OpenAI errors
// into messages people (and the Firdam team) can act on.

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

const MAX_RETRIES = 2;

/** POSTs to Chat Completions, retrying brief rate limits (not quota errors). */
async function fetchOpenAI(apiKey: string, body: unknown): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body),
    });
    if (res.status !== 429 || attempt >= MAX_RETRIES) return res;

    // Out of credit won't fix itself by waiting — return straight away.
    const text = await res.clone().text();
    if (/insufficient_quota|billing/i.test(text)) return res;

    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : 1500 * (attempt + 1);
    await new Promise((r) => setTimeout(r, waitMs));
  }
}

interface OpenAIFailure {
  /** HTTP status to send back to the app. */
  status: number;
  /** Friendly message for the person using the app. */
  message: string;
  /** Short machine code, e.g. `ai_quota`, `ai_busy`, `ai_key`. */
  code: string;
}

/** Reads a failed OpenAI response, logs the details and returns a friendly error. */
async function describeOpenAIFailure(res: Response): Promise<OpenAIFailure> {
  const text = await res.text().catch(() => "");
  let type = "";
  let detail = "";
  try {
    const parsed = JSON.parse(text) as { error?: { type?: string; code?: string; message?: string } };
    type = parsed.error?.code ?? parsed.error?.type ?? "";
    detail = parsed.error?.message ?? "";
  } catch {
    detail = text.slice(0, 300);
  }
  // Visible in Supabase → Edge Functions → Logs.
  console.error(`OpenAI ${res.status} ${type}: ${detail}`);

  if (res.status === 429 && /insufficient_quota/.test(type + detail)) {
    return {
      status: 503,
      code: "ai_quota",
      message:
        "The AI service has run out of credit. The Firdam team needs to add credit to the OpenAI account (platform.openai.com → Billing).",
    };
  }
  if (res.status === 429) {
    return { status: 503, code: "ai_busy", message: "The AI is busy right now. Please try again in a minute." };
  }
  if (res.status === 401 || res.status === 403) {
    return {
      status: 503,
      code: "ai_key",
      message: "The AI key isn't valid. The Firdam team needs to update OPENAI_API_KEY in Supabase.",
    };
  }
  if (res.status === 404 && /model/i.test(detail)) {
    return { status: 503, code: "ai_model", message: "This AI account can't use the selected model yet." };
  }
  return { status: 502, code: "ai_error", message: "The AI couldn't answer just now. Please try again." };
}

// ── inlined from supabase/functions/_shared/pantry-engine.ts ──
// ── inlined from pantry-units.ts ──
/**
 * Ingredient names and amounts: matching a recipe's "chicken thighs" to the
 * pantry's "Chicken", and converting between grams, millilitres and pieces
 * (1 potato ≈ 200 g, 1 cup rice ≈ 190 g) so recipes and pantry can be compared.
 */

type Base = 'g' | 'ml' | 'pc';

// ── Names ────────────────────────────────────────────────────────────

/** Words that describe preparation or quality, not what the food is. */
const DESCRIPTORS = new Set([
  'fresh', 'freshly', 'dried', 'dry', 'chopped', 'sliced', 'diced', 'minced', 'grated', 'crushed', 'mashed', 'ground',
  'whole', 'plain', 'unsalted', 'salted', 'large', 'small', 'medium', 'ripe', 'boneless', 'skinless', 'skin-on',
  'bone-in', 'warm', 'cold', 'hot', 'cooked', 'uncooked', 'raw', 'frozen', 'canned', 'tinned', 'drained', 'rinsed',
  'peeled', 'pitted', 'extra', 'virgin', 'light', 'dark', 'fine', 'finely', 'coarse', 'roughly', 'thinly', 'thick',
  'organic', 'halal', 'good', 'quality', 'free-range', 'lean', 'full-fat', 'low-fat', 'shredded', 'toasted', 'roasted',
  'boiled', 'soft', 'hard', 'baby', 'young', 'mixed', 'assorted', 'of', 'and', 'or', 'the', 'a', 'for', 'to', 'serve',
  'serving', 'garnish', 'optional', 'room', 'temperature', 'store-bought', 'homemade', 'ready-made', 'pieces', 'piece',
]);

const SYNONYMS: Record<string, string> = {
  chiken: 'chicken', aubergine: 'eggplant', courgette: 'zucchini', coriander: 'cilantro', capsicum: 'bell pepper',
  yoghurt: 'yogurt', mince: 'minced meat', prawn: 'shrimp', chilli: 'chili', chile: 'chili', chillies: 'chili',
  chilies: 'chili', scallion: 'spring onion', 'green onion': 'spring onion', garbanzo: 'chickpea', 'icing sugar': 'sugar',
  'caster sugar': 'sugar', 'granulated sugar': 'sugar', 'white sugar': 'sugar', 'brown sugar': 'sugar',
  'all-purpose flour': 'flour', 'plain flour': 'flour', 'self-raising flour': 'flour', 'bread flour': 'flour',
  'sunflower oil': 'oil', 'vegetable oil': 'oil', 'canola oil': 'oil', 'rapeseed oil': 'oil', 'cooking oil': 'oil',
  'olive oil': 'olive oil', 'whole milk': 'milk', 'semi-skimmed milk': 'milk', 'skimmed milk': 'milk',
};

function singular(word: string): string {
  if (word.length <= 3) return word;
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (/(tomato|potato|mango)es$/.test(word)) return word.slice(0, -2);
  if (word.endsWith('ves')) return word.slice(0, -3) + 'f';
  if (word.endsWith('ses') || word.endsWith('xes') || word.endsWith('ches') || word.endsWith('shes')) return word.slice(0, -2);
  if (word.endsWith('s') && !word.endsWith('ss') && !word.endsWith('us')) return word.slice(0, -1);
  return word;
}

/** "Boneless chicken thighs" → "chicken thigh"; "Plain flour" → "flour". */
function ingredientKey(name: string): string {
  let s = name.toLowerCase().replace(/\(.*?\)/g, ' ').replace(/[’']/g, '').replace(/[^a-z\s-]/g, ' ').replace(/\s+/g, ' ').trim();
  if (SYNONYMS[s]) return SYNONYMS[s]!;
  const words = s
    .split(' ')
    .map((w) => SYNONYMS[w] ?? w)
    .join(' ')
    .split(' ')
    .filter((w) => w && !DESCRIPTORS.has(w))
    .map(singular);
  s = words.join(' ').trim();
  return SYNONYMS[s] ?? s;
}

const PROTEINS = ['chicken', 'beef', 'lamb', 'mutton', 'goat', 'veal', 'turkey', 'fish', 'salmon', 'tuna', 'shrimp'];

/**
 * How well a pantry item covers a recipe ingredient (0 = not at all).
 * 3 = same food, 2 = pantry name is a broader word ("chicken" covers
 * "chicken thigh"), 1 = same meat, different cut ("chicken breast" for "chicken thigh").
 */
function matchScore(pantryName: string, ingredientName: string): number {
  const p = ingredientKey(pantryName);
  const n = ingredientKey(ingredientName);
  if (!p || !n) return 0;
  if (p === n) return 3;
  const pw = p.split(' ');
  const nw = n.split(' ');
  if (pw.every((w) => nw.includes(w))) {
    // "oil" shouldn't cover "olive oil"… but does cover "vegetable oil" (already "oil").
    if (p === 'oil' && n.includes('olive')) return 1;
    return 2;
  }
  if (nw.every((w) => pw.includes(w)) && nw.length >= 1 && !/^(oil|sugar|flour|rice|milk)$/.test(n)) return 2;
  const protein = PROTEINS.find((x) => pw.includes(x) && nw.includes(x));
  if (protein) return 1;
  return 0;
}

// ── Always-available basics ──────────────────────────────────────────

const BASIC_RE =
  /\b(salt|water|ice|cumin|paprika|turmeric|cinnamon|cardamom|clove|nutmeg|chili flake|chili powder|cayenne|garam masala|curry powder|baharat|sumac|zaatar|ras el hanout|allspice|bay leaf|oregano|thyme|black pepper|white pepper|peppercorn|saffron|ginger powder|mixed spice|seven spice|stock cube|bouillon|baking powder|baking soda|bicarbonate|vanilla powder|vinegar|yeast|coriander seed|fennel seed|mustard seed|nigella|fenugreek|dried mint|dried lime|berbere|five spice|spice)\b/;

/** Salt, water and dried spices: assumed in every kitchen, never "missing" or deducted. */
function isBasic(name: string): boolean {
  const n = ingredientKey(name).replace(/-/g, ' ');
  const raw = name.toLowerCase();
  return BASIC_RE.test(n) || /\bground\b/.test(raw) && !/\b(beef|lamb|meat|chicken|turkey|almond)\b/.test(raw);
}

// ── Amounts ──────────────────────────────────────────────────────────

const MASS: Record<string, number> = { g: 1, gram: 1, grams: 1, kg: 1000, kilo: 1000, oz: 28.35, lb: 453.6, lbs: 453.6 };
const VOLUME: Record<string, number> = {
  ml: 1, l: 1000, litre: 1000, liter: 1000, tsp: 5, teaspoon: 5, tbsp: 15, tablespoon: 15, cup: 240, cups: 240,
};
const COUNT = new Set(['pieces', 'piece', 'pc', 'pcs', 'cloves', 'clove', 'slices', 'slice', 'whole', 'can', 'cans', 'tin']);

/** Units that only say "some" (we can't measure a pinch or a handful). */
const PRESENCE_ONLY = new Set(['pinch', 'handful', 'bunch', 'to taste', 'pack', 'bottle', 'box', 'bag', 'jar', 'sprig', '']);

/** Typical weight of one piece, by key word (last match wins for specificity). */
const PIECE_GRAMS: [RegExp, number][] = [
  [/potato/, 200], [/sweet potato/, 250], [/onion/, 150], [/red onion/, 150], [/shallot/, 30], [/spring onion/, 15],
  [/tomato/, 120], [/cherry tomato/, 15], [/garlic/, 5], [/lemon/, 100], [/lime/, 60], [/orange/, 180],
  [/carrot/, 70], [/bell pepper|red pepper|green pepper|yellow pepper/, 150], [/chili|chilli|jalapeno|scotch bonnet/, 15],
  [/cucumber/, 300], [/eggplant/, 300], [/zucchini/, 200], [/apple/, 180], [/banana/, 120], [/avocado/, 170],
  [/mango/, 300], [/egg\b/, 55], [/chicken breast/, 200], [/chicken thigh/, 120], [/chicken drumstick|drumstick/, 110],
  [/chicken wing/, 90], [/whole chicken/, 1500], [/pita|pitta|flatbread|naan|tortilla|wrap|roti|chapati/, 70],
  [/bread roll|bun/, 60], [/date/, 8], [/fig/, 50], [/okra/, 12], [/cabbage/, 900], [/cauliflower/, 600],
  [/broccoli/, 350], [/lettuce/, 400], [/mushroom/, 20], [/plantain/, 250], [/pear/, 180], [/peach/, 150],
  [/beetroot|beet/, 150], [/turnip/, 150], [/leek/, 200], [/celery/, 40], [/ginger/, 30], [/cinnamon stick/, 3],
  [/cardamom pod/, 0.3], [/lemongrass/, 20], [/can|tin/, 400],
];

/** Grams per millilitre, for converting cups/spoons of dry foods to weight. */
const DENSITY: [RegExp, number][] = [
  [/rice/, 0.8], [/flour|semolina|cornflour|cornstarch/, 0.55], [/sugar/, 0.85], [/oil|ghee/, 0.92],
  [/butter/, 0.96], [/milk|yogurt|cream|labneh/, 1.03], [/honey|molasses|syrup/, 1.4], [/lentil|split pea/, 0.8],
  [/chickpea|bean/, 0.75], [/bulgur|couscous|freekeh|quinoa/, 0.75], [/oat/, 0.4], [/pasta|noodle|vermicelli|orzo/, 0.45],
  [/nut|almond|walnut|pistachio|cashew|peanut/, 0.6], [/raisin|date/, 0.65], [/coconut/, 0.35], [/cheese/, 0.45],
  [/tomato paste|tomato puree|tahini|paste/, 1.1], [/water|juice|stock|broth|vinegar|sauce/, 1.0],
];

function lookup(table: [RegExp, number][], name: string): number | null {
  const n = ingredientKey(name);
  let found: number | null = null;
  for (const [re, v] of table) if (re.test(n)) found = v;
  return found;
}

const gramsPerPiece = (name: string) => lookup(PIECE_GRAMS, name);
const density = (name: string) => lookup(DENSITY, name);

function normUnit(unit: string | null | undefined): string {
  return (unit ?? '').toLowerCase().trim();
}

/** True when an amount in this unit can't really be measured (a pinch, a bunch, a pack). */
function isPresenceOnly(unit: string | null | undefined, quantity: number | null | undefined): boolean {
  const u = normUnit(unit);
  return quantity == null || quantity <= 0 || PRESENCE_ONLY.has(u) || (!MASS[u] && !VOLUME[u] && !COUNT.has(u));
}

/** Amount in its natural base (g, ml or pieces), or null if it can't be measured. */
function toBase(quantity: number | null | undefined, unit: string | null | undefined, name: string): { amount: number; base: Base } | null {
  if (isPresenceOnly(unit, quantity)) return null;
  const u = normUnit(unit);
  if (MASS[u]) return { amount: quantity! * MASS[u]!, base: 'g' };
  if (VOLUME[u]) return { amount: quantity! * VOLUME[u]!, base: 'ml' };
  if (u === 'can' || u === 'cans' || u === 'tin') return { amount: quantity! * 400, base: 'g' };
  return { amount: quantity!, base: 'pc' };
}

/** Converts between g, ml and pieces for a given food. Null when we don't know how. */
function convertBase(amount: number, from: Base, to: Base, name: string): number | null {
  if (from === to) return amount;
  const d = density(name);
  const p = gramsPerPiece(name);
  const toGrams = (a: number, b: Base): number | null => (b === 'g' ? a : b === 'ml' ? (d ? a * d : null) : p ? a * p : null);
  const g = toGrams(amount, from);
  if (g == null) return null;
  if (to === 'g') return g;
  if (to === 'ml') return d ? g / d : null;
  return p ? g / p : null;
}

/** Converts an amount into a pantry item's own unit (e.g. 3 potatoes → kg). */
function toUnit(amount: number, base: Base, unit: string, name: string): number | null {
  const target = toBase(1, unit, name);
  if (!target) return null;
  const converted = convertBase(amount, base, target.base, name);
  return converted == null ? null : converted / target.amount;
}

// ── Display ──────────────────────────────────────────────────────────

const round = (n: number, step: number) => Math.round(n / step) * step;

/** "1.25 kg", "800 g", "3 pieces", "2 tbsp". */
function formatAmount(quantity: number | null | undefined, unit: string | null | undefined): string {
  const u = normUnit(unit);
  if (quantity == null || quantity <= 0) return u === 'to taste' ? 'to taste' : 'some';
  if (u === 'g' && quantity >= 1000) return `${+(quantity / 1000).toFixed(2)} kg`;
  if (u === 'ml' && quantity >= 1000) return `${+(quantity / 1000).toFixed(2)} L`;
  const n = quantity >= 100 ? round(quantity, 5) : quantity >= 10 ? Math.round(quantity) : +quantity.toFixed(quantity < 1 ? 2 : 1);
  if (u === 'pieces' || u === 'piece') return `${n} ${n === 1 ? 'piece' : 'pieces'}`;
  if (!u) return String(n);
  return `${n} ${u === 'l' ? 'L' : unit}`;
}

/** Picks a friendly unit for a base amount: pieces for countable foods, else g/ml. */
function friendly(amount: number, base: Base, name: string): { quantity: number; unit: string } {
  if (base === 'pc') return { quantity: Math.ceil(amount - 0.05), unit: 'pieces' };
  const p = gramsPerPiece(name);
  if (p && p >= 30) {
    const grams = base === 'g' ? amount : convertBase(amount, base, 'g', name);
    if (grams != null) return { quantity: Math.max(1, Math.ceil(grams / p - 0.15)), unit: 'pieces' };
  }
  if (base === 'g') return amount >= 1000 ? { quantity: +(amount / 1000).toFixed(2), unit: 'kg' } : { quantity: Math.ceil(amount / 10) * 10 || amount, unit: 'g' };
  return amount >= 1000 ? { quantity: +(amount / 1000).toFixed(2), unit: 'L' } : { quantity: Math.ceil(amount / 10) * 10 || amount, unit: 'ml' };
}

// ── Adding amounts ───────────────────────────────────────────────────

interface Amount {
  quantity: number | null;
  unit: string | null;
}

/** A number with no unit ("6 eggs") counts pieces. */
function measured(a: Amount): Amount {
  const u = normUnit(a.unit);
  return a.quantity != null && a.quantity > 0 && !u ? { quantity: a.quantity, unit: 'pieces' } : a;
}

/**
 * Adds two amounts of the same food, keeping the first one's unit when it can:
 *   2 pieces + 3 pcs potato → 5 pieces;  2 kg + 3 pieces potato → 2.6 kg;  200 g + 1 cup rice → 392 g.
 * An unmeasured amount ("to taste", "a bunch") adds nothing to a measured one.
 * Returns null when the two can't be added (e.g. 2 cups + 3 pieces of something we can't weigh).
 */
function addAmounts(first: Amount, second: Amount, name: string): Amount | null {
  const a = measured(first);
  const b = measured(second);
  const ba = toBase(a.quantity, a.unit, name);
  const bb = toBase(b.quantity, b.unit, name);
  if (!ba && !bb) return normUnit(a.unit) === normUnit(b.unit) || !b.unit || normUnit(b.unit) === 'to taste' ? first : !a.unit || normUnit(a.unit) === 'to taste' ? second : null;
  if (!bb) return first;
  if (!ba) return second;
  if (normUnit(a.unit) === normUnit(b.unit)) return { quantity: +(a.quantity! + b.quantity!).toFixed(2), unit: first.unit };
  const extra = convertBase(bb.amount, bb.base, ba.base, name);
  if (extra != null) {
    const inFirstUnit = toUnit(ba.amount + extra, ba.base, a.unit!, name);
    if (inFirstUnit != null) return { quantity: +inFirstUnit.toFixed(2), unit: first.unit };
  }
  // The first unit can't hold it (e.g. pieces of something we can't weigh): try the second's.
  const back = convertBase(ba.amount, ba.base, bb.base, name);
  if (back != null) {
    const inSecondUnit = toUnit(bb.amount + back, bb.base, b.unit!, name);
    if (inSecondUnit != null) return { quantity: +inSecondUnit.toFixed(2), unit: second.unit };
  }
  return null;
}

/**
 * Compares what recipes need with what's in the pantry — with real amounts,
 * scaled to the family's portions — and works out what to take out of the
 * pantry after cooking.
 */

type Level = 'full' | 'half' | 'low' | 'out';

interface PantryLike {
  id: string;
  name: string;
  quantity: number;
  unit: string;
  tracking?: 'count' | 'level' | null;
  level?: Level | null;
  expiration_date?: string | null;
}

interface Need {
  name: string;
  quantity: number | null;
  unit: string;
  optional?: boolean;
}

type LineStatus =
  | 'basic' // salt, water, spices — assumed
  | 'optional'
  | 'enough'
  | 'have-some' // you have it; amount can't be compared (a bunch, a pack)
  | 'staple' // tracked by level (rice, flour…) and not out
  | 'staple-low'
  | 'short' // you have some, not enough
  | 'missing';

interface Line {
  need: Need;
  /** Amount needed after scaling to portions (in the recipe's unit). */
  scaled: number | null;
  item: PantryLike | null;
  status: LineStatus;
  /** How much to take from the pantry item, in the item's unit (count-tracked items only). */
  use: number | null;
  /** What to buy, in a friendly unit. */
  shortfall: { name: string; quantity: number | null; unit: string } | null;
  neededText: string;
  haveText: string;
}

interface RecipeCheck {
  lines: Line[];
  shortCount: number;
  missingCount: number;
  /** ready = cook now; almost = a few things short/missing; far = mostly missing. */
  verdict: 'ready' | 'almost' | 'far';
}

/** Tracks what's left of each pantry item while planning several meals. */
class Ledger {
  private left = new Map<string, number>();
  constructor(pantry: PantryLike[]) {
    for (const p of pantry) this.left.set(p.id, Number(p.quantity) || 0);
  }
  get(item: PantryLike) {
    return this.left.get(item.id) ?? (Number(item.quantity) || 0);
  }
  take(item: PantryLike, amount: number) {
    this.left.set(item.id, Math.max(0, this.get(item) - amount));
  }
}

function available(item: PantryLike, ledger: Ledger): boolean {
  if (item.tracking === 'level') return item.level !== 'out';
  return ledger.get(item) > 0;
}

function bestItem(name: string, pantry: PantryLike[], ledger: Ledger): PantryLike | null {
  let best: PantryLike | null = null;
  let bestScore = 0;
  for (const p of pantry) {
    if (!available(p, ledger)) continue;
    const s = matchScore(p.name, name);
    if (s > bestScore) {
      best = p;
      bestScore = s;
    }
  }
  return best;
}

function shortfallFor(need: Need, scaled: number | null, missingInNeedUnit: number | null) {
  if (missingInNeedUnit == null || scaled == null) return { name: need.name, quantity: null, unit: '' };
  const base = toBase(missingInNeedUnit, need.unit, need.name);
  if (!base) return { name: need.name, quantity: null, unit: '' };
  const f = friendly(base.amount, base.base, need.name);
  return { name: need.name, quantity: f.quantity, unit: f.unit };
}

/**
 * Checks a recipe's ingredients against the pantry.
 * `factor` scales the recipe (family portions ÷ recipe servings).
 * With `commit`, amounts used are taken from the ledger (for weekly plans).
 */
function checkNeeds(
  needs: Need[],
  pantry: PantryLike[],
  opts: { factor?: number; ledger?: Ledger; commit?: boolean } = {}
): RecipeCheck {
  const factor = opts.factor ?? 1;
  const ledger = opts.ledger ?? new Ledger(pantry);
  const lines: Line[] = needs.map((need) => {
    const scaled = need.quantity != null && need.quantity > 0 ? need.quantity * factor : null;
    const countable = /^(pieces?|cloves?|slices?)$/i.test(need.unit.trim());
    const neededText = formatAmount(countable && scaled != null ? Math.ceil(scaled * 2 - 0.2) / 2 : scaled, need.unit);
    const base: Omit<Line, 'status'> = { need, scaled, item: null, use: null, shortfall: null, neededText, haveText: '' };

    if (need.optional) return { ...base, status: 'optional' };
    if (isBasic(need.name)) return { ...base, status: 'basic' };

    const item = bestItem(need.name, pantry, ledger);
    if (!item) return { ...base, status: 'missing', shortfall: shortfallFor(need, scaled, scaled), haveText: 'none' };

    if (item.tracking === 'level') {
      return {
        ...base,
        item,
        status: item.level === 'low' ? 'staple-low' : 'staple',
        haveText: item.level === 'low' ? 'running low' : item.level === 'half' ? 'half left' : 'plenty',
      };
    }

    const have = ledger.get(item);
    const haveText = formatAmount(have, item.unit);
    const needBase = toBase(scaled, need.unit, need.name);
    if (!needBase || isPresenceOnly(item.unit, have)) return { ...base, item, status: 'have-some', haveText };

    const needInItemUnit = toUnit(needBase.amount, needBase.base, item.unit, need.name) ?? toUnit(needBase.amount, needBase.base, item.unit, item.name);
    if (needInItemUnit == null) return { ...base, item, status: 'have-some', haveText };

    if (have >= needInItemUnit * 0.97) {
      if (opts.commit) ledger.take(item, needInItemUnit);
      return { ...base, item, status: 'enough', use: needInItemUnit, haveText };
    }
    // Not enough: use what there is, buy the rest.
    const itemBase = toBase(needInItemUnit - have, item.unit, item.name);
    const missingNeedUnit =
      itemBase && scaled != null
        ? (() => {
            const inNeedBase = convertBase(itemBase.amount, itemBase.base, needBase.base, need.name);
            const perUnit = toBase(1, need.unit, need.name);
            return inNeedBase != null && perUnit ? inNeedBase / perUnit.amount : null;
          })()
        : null;
    if (opts.commit) ledger.take(item, have);
    return {
      ...base,
      item,
      status: 'short',
      use: have,
      haveText,
      shortfall: shortfallFor(need, scaled, missingNeedUnit ?? scaled),
    };
  });

  const counted = lines.filter((l) => l.status !== 'basic' && l.status !== 'optional');
  const missingCount = counted.filter((l) => l.status === 'missing').length;
  const shortCount = counted.filter((l) => l.status === 'short').length;
  const gaps = missingCount + shortCount;
  const verdict: RecipeCheck['verdict'] =
    gaps === 0 ? 'ready' : gaps <= Math.max(2, Math.ceil(counted.length * 0.35)) ? 'almost' : 'far';
  return { lines, shortCount, missingCount, verdict };
}

interface Deduction {
  item: PantryLike;
  /** Amount taken, in the item's unit. */
  use: number;
  newQuantity: number;
}

/** What cooking this recipe takes out of the pantry (count-tracked items only). */
function deductionsFor(check: RecipeCheck): Deduction[] {
  const byItem = new Map<string, Deduction>();
  for (const l of check.lines) {
    if (!l.item || l.use == null || l.use <= 0 || l.item.tracking === 'level') continue;
    const prev = byItem.get(l.item.id);
    const use = (prev?.use ?? 0) + l.use;
    const q = Number(l.item.quantity) || 0;
    byItem.set(l.item.id, { item: l.item, use: Math.min(use, q), newQuantity: Math.max(0, +(q - use).toFixed(3)) });
  }
  return Array.from(byItem.values());
}

/** Merges shortfalls of the same food across several recipes. */
function mergeShortfalls(lists: { name: string; quantity: number | null; unit: string }[][]) {
  // Same food under different names or units ("potato", 2 kg + "potatoes", 3 pieces) becomes one line.
  const out = new Map<string, { name: string; quantity: number | null; unit: string }[]>();
  for (const list of lists) {
    for (const s of list) {
      const key = ingredientKey(s.name) || s.name.toLowerCase();
      const group = out.get(key) ?? [];
      let merged = false;
      for (let i = 0; i < group.length && !merged; i++) {
        const sum = addAmounts(group[i]!, s, s.name);
        if (sum) {
          group[i] = { name: group[i]!.name, quantity: sum.quantity, unit: sum.unit ?? '' };
          merged = true;
        }
      }
      if (!merged) group.push({ ...s });
      out.set(key, group);
    }
  }
  return Array.from(out.values()).flat();
}

// ── inlined from supabase/functions/_shared/pantry-portions.ts ──
/** Family portions: adult (13+) = 1, child 6–12 = ¾, under 6 = ½. Shared by the app and the Companion. */

interface MemberLike {
  birth_date: string | null;
  relationship: string;
}

function portionFor(member: MemberLike): number {
  if (member.birth_date) {
    const born = new Date(member.birth_date);
    if (!Number.isNaN(born.getTime())) {
      const age = (Date.now() - born.getTime()) / (365.25 * 24 * 3600 * 1000);
      if (age < 6) return 0.5;
      if (age < 13) return 0.75;
      return 1;
    }
  }
  // No birth date: assume children are school-age, everyone else an adult.
  return member.relationship === 'Son' || member.relationship === 'Daughter' ? 0.75 : 1;
}

interface Household {
  /** Total portions to cook for, rounded to ¼. */
  portions: number;
  people: number;
  children: number;
}

function householdFrom(members: MemberLike[]): Household {
  // The account holder counts too, unless they've added themselves as "Self".
  const hasSelf = members.some((m) => m.relationship === 'Self');
  const raw = (hasSelf ? 0 : 1) + members.reduce((sum, m) => sum + portionFor(m), 0);
  return {
    portions: Math.max(1, Math.round(raw * 4) / 4),
    people: members.length + (hasSelf ? 0 : 1),
    children: members.filter((m) => portionFor(m) < 1).length,
  };
}

function formatPortions(p: number): string {
  const whole = Math.floor(p);
  const frac = p - whole;
  const f = frac === 0.25 ? '¼' : frac === 0.5 ? '½' : frac === 0.75 ? '¾' : '';
  return `${whole || (f ? '' : '0')}${f}`;
}

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

function env_shared(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env_shared("SUPABASE_URL");
  const anon = env_shared("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env_shared("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── companion ──
/**
 * Firdam AI Family Companion.
 *
 * POST {
 *   messages: { role: "user" | "assistant", content: string }[],
 *   today: "YYYY-MM-DD", timezone: "America/Toronto",
 *   prayerTimes?: Record<string, string>, location?: string
 * }
 * → { reply: string, actions: { type: string, summary: string }[] }
 *
 * The function reads the signed-in user's own data (with the service role,
 * always filtered by their user id) to give grounded answers, and can take
 * a few safe actions on their behalf via tool calls.
 *
 * Secrets: OPENAI_API_KEY (SUPABASE_URL / SERVICE_ROLE_KEY are provided).
 */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

const MODEL = "gpt-4o-mini";
const MAX_HISTORY = 10;
const MAX_TOOL_ROUNDS = 3;

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

// ── Data access (service role, always scoped to the user) ───────────────
async function rest<T>(path: string, init?: RequestInit): Promise<T> {
  const url = env("SUPABASE_URL");
  const key = env("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) throw new Error("Supabase credentials missing");
  const res = await fetch(`${url}/rest/v1/${path}`, {
    ...init,
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) throw new Error(`Data error ${res.status}: ${await res.text()}`);
  const text = await res.text();
  return (text ? JSON.parse(text) : null) as T;
}

/** Reads a table for this user; returns [] if the table is missing or errors. */
/**
 * Rows the user can see. For shared household tables, pass the household id
 * so items other family members added are included too.
 */
async function mine<T>(table: string, userId: string, query = "", householdId?: string | null): Promise<T[]> {
  const who = householdId
    ? `or=(user_id.eq.${encodeURIComponent(userId)},household_id.eq.${encodeURIComponent(householdId)})`
    : `user_id=eq.${encodeURIComponent(userId)}`;
  try {
    return await rest<T[]>(`${table}?${who}${query ? `&${query}` : ""}`);
  } catch {
    return [];
  }
}

function addDays(iso: string, n: number): string {
  const d = new Date(`${iso}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
}

interface Ctx {
  userId: string;
  today: string;
  /** Shared household (Family+), so new items are visible to the whole family. */
  householdId?: string | null;
}

async function buildContext(ctx: Ctx, extras: { prayerTimes?: Record<string, string>; location?: string; timezone?: string }) {
  const { userId, today } = ctx;
  const in7 = addDays(today, 7);
  const in30 = addDays(today, 30);
  const monthStart = `${today.slice(0, 7)}-01`;
  const hh = ctx.householdId ?? null;

  const [profile, members, tasks, events, plans, pantry, groceries, categories, spend, goals, quran] = await Promise.all([
    rest<{ first_name: string | null }[]>(`profiles?id=eq.${userId}&select=first_name`).catch(() => []),
    mine<{ first_name: string; relationship: string; birth_date: string | null }>(
      "family_members",
      userId,
      "select=first_name,relationship,birth_date",
      hh,
    ),
    mine<{ title: string; scheduled_date: string; time: string | null; completed: boolean; priority: string }>(
      "planner_tasks",
      userId,
      `select=title,scheduled_date,time,completed,priority&scheduled_date=gte.${today}&scheduled_date=lte.${in7}&order=scheduled_date`,
      hh,
    ),
    mine<{ title: string; kind: string; starts_on: string; start_time: string | null; repeats_yearly: boolean }>(
      "family_events",
      userId,
      "select=title,kind,starts_on,start_time,repeats_yearly",
      hh,
    ),
    mine<{ plan_data: { weekStartDate?: string; days?: { date: string; meals: { type: string; name: string }[] }[] } }>(
      "meal_plans",
      userId,
      "select=plan_data&order=created_at.desc&limit=3",
      hh,
    ),
    mine<{ name: string; quantity: number; unit: string; expiration_date: string | null; tracking: string | null; level: string | null }>(
      "pantry_items",
      userId,
      "select=name,quantity,unit,expiration_date,tracking,level",
      hh,
    ),
    mine<{ name: string; quantity: number | null; unit: string | null }>(
      "grocery_items",
      userId,
      "select=name,quantity,unit&checked=eq.false",
      hh,
    ),
    mine<{ name: string; monthly_limit: number | null }>("budget_categories", userId, "select=name,monthly_limit"),
    mine<{ amount: number; type: string }>(
      "budget_transactions",
      userId,
      `select=amount,type&occurred_on=gte.${monthStart}`,
    ),
    mine<{ name: string; target: number; saved: number }>("savings_goals", userId, "select=name,target,saved"),
    mine<{ pages: number }>("quran_reading_sessions", userId, `select=pages&read_on=eq.${today}`),
  ]);

  // Upcoming events, including yearly repeats.
  const upcoming = events
    .map((e) => {
      let date = e.starts_on;
      if (e.repeats_yearly) {
        date = `${today.slice(0, 4)}${e.starts_on.slice(4)}`;
        if (date < today) date = `${Number(today.slice(0, 4)) + 1}${e.starts_on.slice(4)}`;
      }
      return { ...e, date };
    })
    .filter((e) => e.date >= today && e.date <= in30)
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(0, 15);

  const weekMeals = plans
    .flatMap((p) => p.plan_data?.days ?? [])
    .filter((d) => d.date >= today && d.date <= in7)
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((d) => `${d.date}: ${d.meals.map((m) => `${m.type} – ${m.name}`).join("; ")}`);

  const expiringSoon = pantry
    .filter((p) => p.expiration_date && p.expiration_date <= addDays(today, 5))
    .map((p) => `${p.name} (expires ${p.expiration_date})`);

  const income = spend.filter((t) => t.type === "income").reduce((s, t) => s + Number(t.amount), 0);
  const expenses = spend.filter((t) => t.type === "expense").reduce((s, t) => s + Number(t.amount), 0);
  const giving = spend.filter((t) => t.type === "sadaqah" || t.type === "zakat").reduce((s, t) => s + Number(t.amount), 0);
  const budget = categories.reduce((s, c) => s + (c.monthly_limit ? Number(c.monthly_limit) : 0), 0);

  const lines = [
    `Today is ${today}${extras.timezone ? ` (${extras.timezone})` : ""}.`,
    profile[0]?.first_name ? `The user's name is ${profile[0].first_name}.` : "",
    extras.location ? `Location: ${extras.location}.` : "",
    extras.prayerTimes
      ? `Today's prayer times: ${Object.entries(extras.prayerTimes).map(([k, v]) => `${k} ${v}`).join(", ")}.`
      : "",
    members.length
      ? `Family members: ${members.map((m) => `${m.first_name} (${m.relationship}${m.birth_date ? `, born ${m.birth_date}` : ""})`).join(", ")}.`
      : "No family members added yet.",
    tasks.length
      ? `Tasks in the next 7 days: ${tasks.map((t) => `${t.scheduled_date}${t.time ? ` ${t.time}` : ""} ${t.title}${t.completed ? " (done)" : ""}`).join("; ")}.`
      : "No tasks in the next 7 days.",
    upcoming.length
      ? `Family calendar, next 30 days: ${upcoming.map((e) => `${e.date} ${e.title} [${e.kind}]`).join("; ")}.`
      : "Nothing on the family calendar in the next 30 days.",
    weekMeals.length ? `Meal plan this week: ${weekMeals.join(" | ")}.` : "No meal plan for this week.",
    pantry.length
      ? `Pantry (${pantry.length} items): ${pantry
          .slice(0, 60)
          .map((p) => (p.tracking === "level" ? `${p.name} (staple, ${p.level ?? "full"})` : `${p.name} ${formatAmount(Number(p.quantity), p.unit)}`))
          .join(", ")}.`
      : "Pantry is empty.",
    members.length ? `Cook for about ${householdFrom(members).portions} portions (children count as ¾ or ½).` : "",
    expiringSoon.length ? `Expiring soon: ${expiringSoon.join(", ")}.` : "",
    groceries.length
      ? `Shopping list: ${groceries.slice(0, 40).map((g) => `${g.name}${g.quantity ? ` ${g.quantity}${g.unit ? ` ${g.unit}` : ""}` : ""}`).join(", ")}.`
      : "Shopping list is empty.",
    `This month: income ${income.toFixed(2)}, spent ${expenses.toFixed(2)}${budget ? ` of a ${budget.toFixed(2)} budget` : ""}, sadaqah/zakat ${giving.toFixed(2)}.`,
    goals.length ? `Savings goals: ${goals.map((g) => `${g.name} ${g.saved}/${g.target}`).join(", ")}.` : "",
    `Quran pages read today: ${quran.reduce((s, q) => s + q.pages, 0)}.`,
  ];
  return lines.filter(Boolean).join("\n");
}

// ── Tools the assistant may call ────────────────────────────────────────
const TOOLS = [
  {
    type: "function",
    function: {
      name: "add_task",
      description: "Add a household task to the user's planner.",
      parameters: {
        type: "object",
        properties: {
          title: { type: "string" },
          date: { type: "string", description: "YYYY-MM-DD" },
          time: { type: "string", description: "HH:MM, optional" },
          priority: { type: "string", enum: ["high", "medium", "low"] },
        },
        required: ["title", "date"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "add_shopping_items",
      description: "Add items to the user's first shopping list.",
      parameters: {
        type: "object",
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: { type: "string" },
                quantity: { type: "number" },
                unit: { type: "string" },
              },
              required: ["name"],
            },
          },
        },
        required: ["items"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "add_family_event",
      description: "Add an event or ceremony to the family calendar.",
      parameters: {
        type: "object",
        properties: {
          title: { type: "string" },
          date: { type: "string", description: "YYYY-MM-DD" },
          time: { type: "string", description: "HH:MM, optional" },
          kind: {
            type: "string",
            enum: ["eid", "aqiqah", "nikah", "walima", "birthday", "anniversary", "school", "appointment", "gathering", "other"],
          },
          location: { type: "string" },
        },
        required: ["title", "date", "kind"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "record_money",
      description: "Record an expense, income, sadaqah or zakat in the budget.",
      parameters: {
        type: "object",
        properties: {
          type: { type: "string", enum: ["expense", "income", "sadaqah", "zakat"] },
          amount: { type: "number" },
          description: { type: "string" },
          date: { type: "string", description: "YYYY-MM-DD" },
        },
        required: ["type", "amount"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "update_pantry",
      description:
        "Update the family pantry when the user says they used, finished, bought or are running low on food. Use amounts the user gave; for vague amounts ('some', 'half') estimate sensibly.",
      parameters: {
        type: "object",
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: { type: "string" },
                change: { type: "string", enum: ["used", "added", "finished", "low", "out", "full"] },
                amount: { type: "number", description: "How much was used or added (omit for finished/low/out/full)" },
                unit: { type: "string", description: "g, kg, ml, L, pieces, cups, tbsp…" },
              },
              required: ["name", "change"],
            },
          },
        },
        required: ["items"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "cooked_recipe",
      description:
        "Record that the family cooked a recipe from the Firdam library, taking its ingredients out of the pantry for the family's portions.",
      parameters: {
        type: "object",
        properties: {
          recipe: { type: "string", description: "Recipe name, e.g. Chicken Karahi" },
          portions: { type: "number", description: "Only if the user said how many people/portions" },
        },
        required: ["recipe"],
      },
    },
  },
];

interface PantryRow extends PantryLike {
  category: string;
  notes: string | null;
}

function snapshot(p: PantryRow) {
  const { id, name, category, quantity, unit, expiration_date, notes, tracking, level } = p;
  return { id, name, category, quantity, unit, expiration_date, notes, tracking, level };
}

/** Applies pantry changes with history (so the family can undo them in the app). */
async function applyPantry(
  ctx: Ctx,
  changes: ({ kind: "update"; item: PantryRow; patch: Record<string, unknown> } | { kind: "delete"; item: PantryRow } | { kind: "insert"; row: Record<string, unknown> })[],
  label: string,
): Promise<string> {
  const batch = crypto.randomUUID();
  const events: Record<string, unknown>[] = [];
  const owner = { user_id: ctx.userId, household_id: ctx.householdId ?? null };
  for (const c of changes) {
    if (c.kind === "update") {
      const rows = await rest<PantryRow[]>(`pantry_items?id=eq.${c.item.id}`, {
        method: "PATCH",
        headers: { Prefer: "return=representation" },
        body: JSON.stringify(c.patch),
      });
      events.push({ ...owner, batch_id: batch, source: "companion", label, pantry_item_id: c.item.id, item_name: c.item.name, before: snapshot(c.item), after: rows[0] ? snapshot(rows[0]) : null });
    } else if (c.kind === "delete") {
      await rest(`pantry_items?id=eq.${c.item.id}`, { method: "DELETE", headers: { Prefer: "return=minimal" } });
      events.push({ ...owner, batch_id: batch, source: "companion", label, pantry_item_id: c.item.id, item_name: c.item.name, before: snapshot(c.item), after: null });
    } else {
      const rows = await rest<PantryRow[]>("pantry_items", {
        method: "POST",
        headers: { Prefer: "return=representation" },
        body: JSON.stringify({ ...owner, ...c.row }),
      });
      if (rows[0]) events.push({ ...owner, batch_id: batch, source: "companion", label, pantry_item_id: rows[0].id, item_name: rows[0].name, before: null, after: snapshot(rows[0]) });
    }
  }
  if (events.length) {
    await rest("pantry_events", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(events) }).catch(() => undefined);
  }
  return batch;
}

async function loadPantry(ctx: Ctx): Promise<PantryRow[]> {
  return await mine<PantryRow>("pantry_items", ctx.userId, "select=*", ctx.householdId);
}

function bestPantryMatch(pantry: PantryRow[], name: string): PantryRow | null {
  let best: PantryRow | null = null;
  let score = 0;
  for (const p of pantry) {
    const s = matchScore(p.name, name);
    if (s > score) {
      best = p;
      score = s;
    }
  }
  return score >= 2 ? best : null;
}

const PANTRY_UNIT_MAP: Record<string, string> = {
  g: "g", gram: "g", grams: "g", kg: "kg", kilo: "kg", ml: "ml", l: "L", litre: "L", liter: "L", piece: "Pieces", pieces: "Pieces",
  pack: "Pack", bag: "Pack", bottle: "Bottle", can: "Can", tin: "Can", box: "Box",
};

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const TIME_RE = /^\d{2}:\d{2}$/;

async function runTool(name: string, args: Record<string, unknown>, ctx: Ctx): Promise<{ result: string; summary?: string }> {
  const { userId, today } = ctx;
  const household_id = ctx.householdId ?? null;
  const str = (v: unknown, max = 200) => (typeof v === "string" ? v.trim().slice(0, max) : "");
  try {
    if (name === "add_task") {
      const title = str(args.title, 160);
      const date = DATE_RE.test(str(args.date)) ? str(args.date) : today;
      const time = TIME_RE.test(str(args.time)) ? str(args.time) : null;
      const priority = ["high", "medium", "low"].includes(str(args.priority)) ? str(args.priority) : "medium";
      if (!title) return { result: "Missing title" };
      await rest("planner_tasks", {
        method: "POST",
        headers: { Prefer: "return=minimal" },
        body: JSON.stringify({ user_id: userId, household_id, title, scheduled_date: date, time, priority }),
      });
      return { result: "Task added", summary: `Added task “${title}” on ${date}${time ? ` at ${time}` : ""}` };
    }
    if (name === "add_shopping_items") {
      const items = (Array.isArray(args.items) ? args.items : []).slice(0, 30) as Record<string, unknown>[];
      if (!items.length) return { result: "No items" };
      const lists = await rest<{ id: string }[]>(
        `grocery_lists?${
          household_id ? `or=(user_id.eq.${userId},household_id.eq.${household_id})` : `user_id=eq.${userId}`
        }&select=id&order=created_at.asc&limit=1`,
      );
      let listId = lists[0]?.id;
      if (!listId) {
        const created = await rest<{ id: string }[]>("grocery_lists", {
          method: "POST",
          headers: { Prefer: "return=representation" },
          body: JSON.stringify({ user_id: userId, household_id, name: "Weekly groceries" }),
        });
        listId = created[0]?.id;
      }
      const rows = items
        .map((i) => ({
          user_id: userId,
          household_id,
          list_id: listId,
          name: str(i.name, 120),
          quantity: typeof i.quantity === "number" && i.quantity > 0 ? i.quantity : null,
          unit: str(i.unit, 20) || null,
          category: "Other",
          note: "Added by your Companion",
        }))
        .filter((r) => r.name);
      await rest("grocery_items", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(rows) });
      return { result: `Added ${rows.length} items`, summary: `Added ${rows.map((r) => r.name).join(", ")} to Shopping` };
    }
    if (name === "add_family_event") {
      const title = str(args.title, 120);
      const date = str(args.date);
      if (!title || !DATE_RE.test(date)) return { result: "Missing title or valid date" };
      const kinds = ["eid", "aqiqah", "nikah", "walima", "birthday", "anniversary", "school", "appointment", "gathering", "other"];
      const kind = kinds.includes(str(args.kind)) ? str(args.kind) : "other";
      const time = TIME_RE.test(str(args.time)) ? str(args.time) : null;
      await rest("family_events", {
        method: "POST",
        headers: { Prefer: "return=minimal" },
        body: JSON.stringify({ user_id: userId, household_id, title, kind, starts_on: date, start_time: time, location: str(args.location) || null }),
      });
      return { result: "Event added", summary: `Added “${title}” to the family calendar on ${date}` };
    }
    if (name === "record_money") {
      const type = ["expense", "income", "sadaqah", "zakat"].includes(str(args.type)) ? str(args.type) : "expense";
      const amount = Number(args.amount);
      if (!Number.isFinite(amount) || amount <= 0) return { result: "Invalid amount" };
      const date = DATE_RE.test(str(args.date)) ? str(args.date) : today;
      await rest("budget_transactions", {
        method: "POST",
        headers: { Prefer: "return=minimal" },
        body: JSON.stringify({
          user_id: userId,
          type,
          amount: Math.round(amount * 100) / 100,
          description: str(args.description) || null,
          occurred_on: date,
        }),
      });
      return { result: "Recorded", summary: `Recorded ${type} of ${amount.toFixed(2)}${str(args.description) ? ` (${str(args.description)})` : ""}` };
    }
    if (name === "update_pantry") {
      const items = (Array.isArray(args.items) ? args.items : []).slice(0, 25) as Record<string, unknown>[];
      if (!items.length) return { result: "No items" };
      const pantry = await loadPantry(ctx);
      const changes: Parameters<typeof applyPantry>[1] = [];
      const done: string[] = [];
      for (const it of items) {
        const itemName = str(it.name, 80);
        const change = str(it.change);
        const amount = typeof it.amount === "number" && it.amount > 0 ? it.amount : null;
        const unit = str(it.unit, 20).toLowerCase().replace(/s$/, "");
        if (!itemName) continue;
        const match = bestPantryMatch(pantry, itemName);
        if (change === "added") {
          const pUnit = PANTRY_UNIT_MAP[unit] ?? (amount ? "Pieces" : "Pack");
          if (match && match.tracking === "level") {
            changes.push({ kind: "update", item: match, patch: { level: "full" } });
            done.push(`${match.name} → full`);
            continue;
          }
          if (match && amount) {
            const base = toBase(amount, pUnit, itemName);
            const inUnit = base ? toUnit(base.amount, base.base, match.unit, itemName) : pUnit === match.unit ? amount : null;
            if (inUnit != null) {
              const q = +(Number(match.quantity) + inUnit).toFixed(3);
              changes.push({ kind: "update", item: match, patch: { quantity: q } });
              done.push(`${match.name} +${formatAmount(amount, pUnit)}`);
              continue;
            }
          }
          changes.push({ kind: "insert", row: { name: itemName.replace(/^\w/, (c) => c.toUpperCase()), category: "Other", quantity: amount ?? 1, unit: pUnit, tracking: "count" } });
          done.push(`added ${itemName}`);
          continue;
        }
        if (!match) {
          done.push(`${itemName} isn't in the pantry`);
          continue;
        }
        if (change === "finished" || (change === "out" && match.tracking !== "level")) {
          if (match.tracking === "level") changes.push({ kind: "update", item: match, patch: { level: "out" } });
          else changes.push({ kind: "delete", item: match });
          done.push(`${match.name} finished`);
        } else if (change === "low" || change === "out" || change === "full") {
          if (match.tracking === "level") {
            changes.push({ kind: "update", item: match, patch: { level: change } });
            done.push(`${match.name} → ${change}`);
          } else if (change === "low") {
            changes.push({ kind: "update", item: match, patch: { quantity: +(Number(match.quantity) / 3).toFixed(2) } });
            done.push(`${match.name} running low`);
          }
        } else if (change === "used") {
          if (match.tracking === "level") {
            done.push(`${match.name} is a staple (still ${match.level ?? "full"})`);
            continue;
          }
          const q = Number(match.quantity) || 0;
          let use: number | null = null;
          if (amount) {
            const base = toBase(amount, PANTRY_UNIT_MAP[unit] ?? (unit || "Pieces"), itemName);
            use = base ? toUnit(base.amount, base.base, match.unit, itemName) : null;
            if (use == null && (PANTRY_UNIT_MAP[unit] ?? "") === match.unit) use = amount;
          }
          if (use == null) use = q / 2;
          const left = +(q - use).toFixed(3);
          changes.push(left <= 0.0001 ? { kind: "delete", item: match } : { kind: "update", item: match, patch: { quantity: left } });
          done.push(left <= 0.0001 ? `${match.name} finished` : `${match.name}: ${formatAmount(left, match.unit)} left`);
        }
      }
      if (!changes.length) return { result: done.join("; ") || "Nothing to change" };
      await applyPantry(ctx, changes, "Told the Companion");
      return { result: `Updated: ${done.join("; ")}`, summary: `Pantry updated: ${done.join("; ")} (you can undo on the Pantry page)` };
    }
    if (name === "cooked_recipe") {
      const recipeName = str(args.recipe, 120);
      if (!recipeName) return { result: "Missing recipe" };
      type R = { id: string; name: string; servings: number | null; recipe_ingredients: { quantity: number | null; unit: string | null; optional: boolean | null; ingredient: { name: string } | null }[] };
      const found = await rest<R[]>(
        `recipes?select=id,name,servings,recipe_ingredients(quantity,unit,optional,ingredient:ingredients(name))&is_active=eq.true&name=ilike.*${encodeURIComponent(recipeName.replace(/[*,()]/g, " "))}*&limit=1`,
      );
      const recipe = found[0];
      if (!recipe) return { result: `No library recipe called "${recipeName}". Offer to update the pantry item by item instead.` };
      let portions = typeof args.portions === "number" && args.portions > 0 ? args.portions : null;
      if (!portions) {
        const members = await mine<{ birth_date: string | null; relationship: string }>("family_members", ctx.userId, "select=birth_date,relationship", ctx.householdId);
        portions = members.length ? householdFrom(members).portions : recipe.servings || 4;
      }
      const pantry = await loadPantry(ctx);
      const needs = recipe.recipe_ingredients
        .filter((i) => i.ingredient?.name)
        .map((i) => ({ name: i.ingredient!.name, quantity: i.quantity != null && Number(i.quantity) > 0 ? Number(i.quantity) : null, unit: i.unit ?? "", optional: !!i.optional }));
      const check = checkNeeds(needs, pantry, { factor: portions / (recipe.servings || portions) });
      const deductions = deductionsFor(check);
      const byId = new Map(pantry.map((p) => [p.id, p]));
      const batch = await applyPantry(
        ctx,
        deductions.map((d) => {
          const item = byId.get(d.item.id)!;
          return d.newQuantity <= 0.0001 ? { kind: "delete" as const, item } : { kind: "update" as const, item, patch: { quantity: d.newQuantity } };
        }),
        `Cooked ${recipe.name}`,
      );
      await rest("cooking_log", {
        method: "POST",
        headers: { Prefer: "return=minimal" },
        body: JSON.stringify({
          user_id: ctx.userId,
          household_id: ctx.householdId ?? null,
          cooked_on: today,
          status: "cooked",
          recipe_key: `c-${recipe.id}`,
          recipe_name: recipe.name,
          servings: portions,
          batch_id: batch,
        }),
      });
      const used = deductions.map((d) => `${d.item.name} −${formatAmount(d.use, d.item.unit)}`).join(", ");
      return {
        result: `Logged ${recipe.name} for ${portions} portions. ${used ? `Took from pantry: ${used}.` : "Nothing tracked in the pantry was used."}`,
        summary: `Cooked ${recipe.name}${used ? ` — pantry updated (${used})` : ""}`,
      };
    }
    return { result: "Unknown tool" };
  } catch (err) {
    return { result: `Failed: ${err instanceof Error ? err.message : "error"}` };
  }
}

const SYSTEM_PROMPT = `You are the Firdam Family Companion, a warm, respectful and practical assistant for Muslim families.

How you help:
- Plan the family's days, meals, shopping, budget, Ramadan and events, using the family data provided below.
- When the user clearly asks you to add, record or schedule something, use the tools. Confirm briefly what you did. Never invent data you weren't given.
- Keep the pantry accurate: when the user mentions using, finishing or buying food ("we used 3 potatoes", "rice is almost gone", "I bought 2 kg chicken"), call update_pantry. When they say they cooked a library recipe, call cooked_recipe.
- When suggesting meals, check the pantry amounts and the family's portions shown below; say what needs buying.
- Keep answers short, clear and kind. Use the user's name occasionally. Use simple Islamic greetings and phrases naturally (e.g. "in sha Allah"), without overdoing it.
- All food suggestions must be halal (no pork, no alcohol, halal meat).

Religious questions:
- You may share general, well-established knowledge (e.g. what breaks the fast, how to pray while travelling), mention where scholars differ, and suggest asking a qualified local scholar for personal rulings. Never issue fatwas or claim certainty on disputed matters. Quote Quran or hadith only if you are certain of the wording and source.

Health, legal and financial matters: give general information only and suggest a professional for personal advice.

Data privacy: only discuss this user's own family data shown below.`;

interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string | null;
  tool_calls?: { id: string; type: "function"; function: { name: string; arguments: string } }[];
  tool_call_id?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 200, headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  try {
    const apiKey = env("OPENAI_API_KEY");
    if (!apiKey) return json({ error: "The Companion is not set up yet.", code: "not_configured" }, 501);

    const user = await getUser(req);
    if (!user) return json({ error: "Please sign in." }, 401);

    const plan = await getPlan(user.id);
    if (plan === "free") {
      const used = await countUsageThisMonth(user.id, "companion");
      if (used >= FREE_COMPANION_MESSAGES_PER_MONTH) {
        return json(
          {
            error: "The Family Companion is part of Premium and Family+. Try “What can I cook?” in Recipes — it’s free.",
            code: "limit_reached",
          },
          402,
        );
      }
    } else {
      const used = await countUsageToday(user.id, "companion");
      if (used >= PAID_COMPANION_MESSAGES_PER_DAY) {
        return json(
          {
            error: `You've reached today's ${PAID_COMPANION_MESSAGES_PER_DAY} Companion messages. They reset in 24 hours.`,
            code: "fair_use",
          },
          429,
        );
      }
    }

    const body = (await req.json().catch(() => ({}))) as {
      messages?: { role: string; content: string }[];
      today?: string;
      timezone?: string;
      prayerTimes?: Record<string, string>;
      location?: string;
    };
    const today = body.today && DATE_RE.test(body.today) ? body.today : new Date().toISOString().slice(0, 10);
    const history = (body.messages ?? [])
      .filter((m) => (m.role === "user" || m.role === "assistant") && typeof m.content === "string" && m.content.trim())
      .slice(-MAX_HISTORY)
      .map((m) => ({ role: m.role as "user" | "assistant", content: m.content.slice(0, 4000) }));
    if (!history.length || history[history.length - 1].role !== "user") {
      return json({ error: "Send a message." }, 400);
    }

    const membership = await rest<{ household_id: string }[]>(
      `household_members?user_id=eq.${user.id}&select=household_id`,
    ).catch(() => []);
    const ctx: Ctx = { userId: user.id, today, householdId: membership[0]?.household_id ?? null };
    const familyContext = await buildContext(ctx, {
      prayerTimes: body.prayerTimes,
      location: typeof body.location === "string" ? body.location.slice(0, 120) : undefined,
      timezone: typeof body.timezone === "string" ? body.timezone.slice(0, 60) : undefined,
    });

    const messages: ChatMessage[] = [
      { role: "system", content: `${SYSTEM_PROMPT}\n\nFamily data:\n${familyContext}` },
      ...history,
    ];
    const actions: { type: string; summary: string }[] = [];

    for (let round = 0; round <= MAX_TOOL_ROUNDS; round++) {
      const res = await fetchOpenAI(apiKey, {
        model: MODEL,
        messages,
        temperature: 0.5,
        max_tokens: 700,
        tools: round < MAX_TOOL_ROUNDS ? TOOLS : undefined,
      });
      if (!res.ok) {
        const fail = await describeOpenAIFailure(res);
        return json({ error: fail.message, code: fail.code }, fail.status);
      }
      const data = (await res.json()) as { choices?: { message?: ChatMessage }[] };
      const msg = data.choices?.[0]?.message;
      if (!msg) return json({ error: "Empty AI response." }, 502);

      if (msg.tool_calls?.length) {
        messages.push({ role: "assistant", content: msg.content ?? null, tool_calls: msg.tool_calls });
        for (const call of msg.tool_calls.slice(0, 5)) {
          let args: Record<string, unknown> = {};
          try {
            args = JSON.parse(call.function.arguments || "{}");
          } catch {
            // leave empty
          }
          const out = await runTool(call.function.name, args, ctx);
          if (out.summary) actions.push({ type: call.function.name, summary: out.summary });
          messages.push({ role: "tool", tool_call_id: call.id, content: out.result });
        }
        continue;
      }

      await recordUsage(user.id, "companion");
      return json({ reply: msg.content ?? "", actions });
    }
    await recordUsage(user.id, "companion");
    return json({ reply: "Done.", actions });
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : "Unknown error" }, 500);
  }
});
