// Single-file copy of supabase/functions/delete-account/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

// Free launch: everyone gets the full app (with the fair-use caps above) and
// nothing is sold. Keep in sync with FREE_LAUNCH in lib/plan/plan.ts.
const FREE_LAUNCH = true;

function env_shared(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env_shared("SUPABASE_URL");
  const anon = env_shared("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env_shared("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  if (FREE_LAUNCH) return "family";
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── delete-account ──
/**
 * Permanently deletes the signed-in user's account (Settings → Delete my account).
 * - cancels an active Stripe subscription (if Stripe is set up),
 * - hands a shared household to another member if the user owns it,
 * - deletes the auth user; every table references auth.users with
 *   ON DELETE CASCADE, so all their rows go with it.
 *
 * POST { confirm: "DELETE" }
 */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}

function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

async function rest<T>(path: string, init: RequestInit = {}): Promise<T> {
  const url = env("SUPABASE_URL")!;
  const key = env("SUPABASE_SERVICE_ROLE_KEY")!;
  const res = await fetch(`${url}/rest/v1/${path}`, {
    ...init,
    headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", ...(init.headers ?? {}) },
  });
  if (!res.ok) throw new Error(`Database error ${res.status}: ${(await res.text()).slice(0, 200)}`);
  const text = await res.text();
  return (text ? JSON.parse(text) : null) as T;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 200, headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Use POST." }, 405);
  try {
    const user = await getUser(req);
    if (!user) return json({ error: "Please sign in." }, 401);
    const body = (await req.json().catch(() => ({}))) as { confirm?: string };
    if (body.confirm !== "DELETE") return json({ error: "Confirmation missing." }, 400);

    // 1. Cancel a live Stripe subscription so they aren't charged again.
    const stripeKey = env("STRIPE_SECRET_KEY");
    const subs = await rest<{ stripe_subscription_id: string | null; status: string }[]>(
      `subscriptions?user_id=eq.${user.id}&select=stripe_subscription_id,status`,
    ).catch(() => []);
    for (const s of subs) {
      if (stripeKey && s.stripe_subscription_id && ["active", "trialing", "past_due", "unpaid"].includes(s.status)) {
        const res = await fetch(`https://api.stripe.com/v1/subscriptions/${s.stripe_subscription_id}`, {
          method: "DELETE",
          headers: { Authorization: `Bearer ${stripeKey}` },
        });
        if (!res.ok && res.status !== 404) {
          return json({ error: "We couldn't cancel your subscription automatically. Please cancel it in Settings first." }, 502);
        }
      }
    }

    // 2. Hand a shared household to the longest-standing other member.
    const owned = await rest<{ id: string }[]>(`households?owner_id=eq.${user.id}&select=id`).catch(() => []);
    for (const h of owned) {
      const others = await rest<{ user_id: string }[]>(
        `household_members?household_id=eq.${h.id}&user_id=neq.${user.id}&select=user_id&order=joined_at.asc&limit=1`,
      );
      if (others[0]) {
        await rest(`households?id=eq.${h.id}`, { method: "PATCH", body: JSON.stringify({ owner_id: others[0].user_id }) });
        await rest(`household_members?household_id=eq.${h.id}&user_id=eq.${others[0].user_id}`, {
          method: "PATCH",
          body: JSON.stringify({ role: "owner" }),
        });
      }
    }

    // 3. Delete the login; everything else cascades.
    const res = await fetch(`${env("SUPABASE_URL")}/auth/v1/admin/users/${user.id}`, {
      method: "DELETE",
      headers: { apikey: env("SUPABASE_SERVICE_ROLE_KEY")!, Authorization: `Bearer ${env("SUPABASE_SERVICE_ROLE_KEY")}` },
    });
    if (!res.ok) {
      console.error("Delete user failed", res.status, await res.text());
      return json({ error: "Something went wrong deleting your account." }, 500);
    }
    return json({ deleted: true });
  } catch (err) {
    console.error(err);
    return json({ error: err instanceof Error ? err.message : "Unexpected error" }, 500);
  }
});
