// Single-file copy of supabase/functions/generate-meal-plan/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/openai.ts ──
// Shared OpenAI helpers: retries short rate limits and turns OpenAI errors
// into messages people (and the Firdam team) can act on.

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

const MAX_RETRIES = 2;

/** POSTs to Chat Completions, retrying brief rate limits (not quota errors). */
async function fetchOpenAI(apiKey: string, body: unknown): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body),
    });
    if (res.status !== 429 || attempt >= MAX_RETRIES) return res;

    // Out of credit won't fix itself by waiting — return straight away.
    const text = await res.clone().text();
    if (/insufficient_quota|billing/i.test(text)) return res;

    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : 1500 * (attempt + 1);
    await new Promise((r) => setTimeout(r, waitMs));
  }
}

interface OpenAIFailure {
  /** HTTP status to send back to the app. */
  status: number;
  /** Friendly message for the person using the app. */
  message: string;
  /** Short machine code, e.g. `ai_quota`, `ai_busy`, `ai_key`. */
  code: string;
}

/** Reads a failed OpenAI response, logs the details and returns a friendly error. */
async function describeOpenAIFailure(res: Response): Promise<OpenAIFailure> {
  const text = await res.text().catch(() => "");
  let type = "";
  let detail = "";
  try {
    const parsed = JSON.parse(text) as { error?: { type?: string; code?: string; message?: string } };
    type = parsed.error?.code ?? parsed.error?.type ?? "";
    detail = parsed.error?.message ?? "";
  } catch {
    detail = text.slice(0, 300);
  }
  // Visible in Supabase → Edge Functions → Logs.
  console.error(`OpenAI ${res.status} ${type}: ${detail}`);

  if (res.status === 429 && /insufficient_quota|credit_balance|no credits|billing/i.test(type + detail)) {
    return {
      status: 503,
      code: "ai_quota",
      message:
        "The AI service has run out of credit. The Firdam team needs to add credit to the OpenAI account (platform.openai.com → Billing).",
    };
  }
  if (res.status === 429) {
    return { status: 503, code: "ai_busy", message: "The AI is busy right now. Please try again in a minute." };
  }
  if (res.status === 401 || res.status === 403) {
    return {
      status: 503,
      code: "ai_key",
      message: "The AI key isn't valid. The Firdam team needs to update OPENAI_API_KEY in Supabase.",
    };
  }
  if (res.status === 404 && /model/i.test(detail)) {
    return { status: 503, code: "ai_model", message: "This AI account can't use the selected model yet." };
  }
  return { status: 502, code: "ai_error", message: "The AI couldn't answer just now. Please try again." };
}

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env("SUPABASE_URL");
  const anon = env("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── generate-meal-plan ──
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

const MODEL = "gpt-4o-mini";

const DAY_NAMES = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

interface MealIngredient {
  name: string;
  quantity: string;
  unit: string;
}

interface PlannedMeal {
  type: string;
  name: string;
  cuisine: string;
  description: string;
  ingredients: MealIngredient[];
  recipe: string[];
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: string;
}

interface PlannedDay {
  dayIndex: number;
  dayName: string;
  date: string;
  meals: PlannedMeal[];
}

interface MealPlanResponse {
  days: PlannedDay[];
}

interface GenerateRequest {
  planningDuration?: number;
  mealTypes?: string[];
  householdSize?: number;
  weekStartDate?: string;
  dietaryPreferences?: string[];
  allergies?: string[];
  cuisinePreferences?: Record<string, string[]>;
  usePantryFirst?: boolean;
  pantryItems?: { name: string; quantity: number; unit: string }[];
}

const SYSTEM_PROMPT = `You are a meal-planning assistant for a Muslim family app.
Generate a complete halal weekly meal plan directly from the user's preferences.

Rules:
1. Every recipe MUST be strictly halal — no pork, no alcohol, no non-halal meat. All meat is assumed halal.
2. Respect all dietary preferences and avoid every listed allergy across ingredients and recipe steps.
3. Honor cuisine preferences per meal type when provided; leave a meal type unconstrained when its list is empty.
4. Each day must contain exactly the requested meal types, in the order given.
5. Maximize variety — avoid repeating the same recipe within the plan.
6. When pantry usage is prioritized, prefer recipes that reuse the listed pantry ingredients.
7. Scale ingredient quantities to the household size.
8. Keep recipes realistic and home-cookable with clear step-by-step instructions.
9. Return ONLY valid JSON matching the requested schema. No markdown, no commentary.`;

function buildUserPrompt(req: GenerateRequest): string {
  const duration = req.planningDuration ?? 7;
  const mealTypes = req.mealTypes ?? ["breakfast", "lunch", "dinner"];
  const household = req.householdSize ?? 4;
  const weekStart = req.weekStartDate ?? "this week";

  const cuisines = req.cuisinePreferences
    ? Object.entries(req.cuisinePreferences)
        .filter(([, list]) => Array.isArray(list) && list.length > 0)
        .map(([type, list]) => `${type}: ${list.join(", ")}`)
        .join("; ")
    : "";

  const pantry =
    req.usePantryFirst && req.pantryItems?.length
      ? `\nPantry available (prioritize recipes using these): ${req.pantryItems
          .map((p) => `${p.quantity} ${p.unit} ${p.name}`)
          .join(", ")}.`
      : "";

  return `Plan ${duration} days of meals.
Meal types per day (in this order): ${mealTypes.join(", ")}.
Household size: ${household} servings.
Week start date: ${weekStart}.
${cuisines ? `Cuisine preferences by meal type: ${cuisines}.` : ""}
${req.dietaryPreferences?.length ? `Dietary: ${req.dietaryPreferences.join(", ")}.` : ""}
${req.allergies?.length ? `Allergies to avoid: ${req.allergies.join(", ")}.` : ""}
${pantry}

Return JSON with this exact shape:
{
  "days": [
    {
      "dayIndex": 0,
      "dayName": "Monday",
      "date": "YYYY-MM-DD",
      "meals": [
        {
          "type": "breakfast",
          "name": "Recipe name",
          "cuisine": "Moroccan",
          "description": "One short sentence.",
          "ingredients": [
            { "name": "oats", "quantity": "1", "unit": "cup" }
          ],
          "recipe": ["Step one.", "Step two."],
          "prepTime": 10,
          "cookTime": 15,
          "servings": ${household},
          "difficulty": "Easy"
        }
      ]
    }
  ]
}
Day names cycle: ${DAY_NAMES.join(", ")}.
Each day's meals array must have exactly ${mealTypes.length} entry/entries, one per requested meal type, in the order given.
prepTime and cookTime are integers in minutes. difficulty is one of: Easy, Medium, Hard.`;
}

function extractJson(text: string): unknown {
  let cleaned = text.trim();
  const fence = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) cleaned = fence[1].trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start !== -1 && end !== -1) {
    cleaned = cleaned.slice(start, end + 1);
  }
  return JSON.parse(cleaned);
}

function isMeal(value: unknown): value is PlannedMeal {
  if (typeof value !== "object" || value === null) return false;
  const m = value as Record<string, unknown>;
  return (
    typeof m.type === "string" &&
    typeof m.name === "string" &&
    typeof m.description === "string" &&
    Array.isArray(m.ingredients) &&
    Array.isArray(m.recipe)
  );
}

function validateResponse(data: unknown): data is MealPlanResponse {
  if (typeof data !== "object" || data === null) return false;
  const obj = data as Record<string, unknown>;
  if (!Array.isArray(obj.days) || obj.days.length === 0) return false;
  return obj.days.every(
    (day) =>
      typeof day === "object" &&
      day !== null &&
      typeof (day as Record<string, unknown>).dayIndex === "number" &&
      Array.isArray((day as Record<string, unknown>).meals) &&
      ((day as Record<string, unknown>).meals as unknown[]).every(isMeal)
  );
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const apiKey = Deno.env.get("OPENAI_API_KEY");
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: "OpenAI API key is not configured." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({ error: "Method not allowed. Use POST." }),
        { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Plan limits: Free users get a few AI plans a month; paid plans are unlimited.
    const user = await getUser(req);
    if (!user) {
      return new Response(
        JSON.stringify({ error: "Please sign in." }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    const plan = await getPlan(user.id);
    {
      const used = await countUsageThisMonth(user.id, "ai_meal_plan");
      if (plan !== "free" && used >= PAID_AI_PLANS_PER_MONTH) {
        return new Response(
          JSON.stringify({
            error: `You've used this month's ${PAID_AI_PLANS_PER_MONTH} AI chef plans. Plans from the recipe library are still unlimited.`,
            code: "fair_use",
          }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (plan === "free" && used >= FREE_AI_PLANS_PER_MONTH) {
        return new Response(
          JSON.stringify({
            error: `You've used your ${FREE_AI_PLANS_PER_MONTH} free AI meal plans this month.`,
            code: "limit_reached",
          }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    const body = (await req.json()) as GenerateRequest;

    const planningDuration = body.planningDuration ?? 7;
    if (
      typeof planningDuration !== "number" ||
      ![3, 5, 7].includes(planningDuration)
    ) {
      return new Response(
        JSON.stringify({ error: "planningDuration must be 3, 5 or 7 days." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const mealTypes = body.mealTypes ?? ["breakfast", "lunch", "dinner"];
    if (!Array.isArray(mealTypes) || mealTypes.length === 0) {
      return new Response(
        JSON.stringify({ error: "mealTypes must be a non-empty array." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const openaiRes = await fetchOpenAI(apiKey, {
        model: MODEL,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: buildUserPrompt(body) },
        ],
        temperature: 0.8,
        // Bounds the cost of one plan (7 days × 4 meals fits comfortably).
        max_tokens: 12000,
        response_format: { type: "json_object" },
      });

    if (!openaiRes.ok) {
      const fail = await describeOpenAIFailure(openaiRes);
      return new Response(JSON.stringify({ error: fail.message, code: fail.code }), {
        status: fail.status,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const openaiJson = (await openaiRes.json()) as {
      choices?: { message?: { content?: string } }[];
    };

    const content = openaiJson.choices?.[0]?.message?.content;
    if (!content) {
      return new Response(
        JSON.stringify({ error: "OpenAI returned an empty response." }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let parsed: unknown;
    try {
      parsed = extractJson(content);
    } catch {
      return new Response(
        JSON.stringify({ error: "Failed to parse OpenAI response as JSON.", raw: content }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!validateResponse(parsed)) {
      return new Response(
        JSON.stringify({ error: "OpenAI response did not match the expected schema.", raw: content }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    await recordUsage(user.id, "ai_meal_plan");

    return new Response(JSON.stringify(parsed as MealPlanResponse), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
