// Single-file copy of supabase/functions/prayer-times/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

interface PrayerTimings {
  Imsak: string;
  Fajr: string;
  Sunrise: string;
  Dhuhr: string;
  Asr: string;
  Maghrib: string;
  Isha: string;
  Midnight: string;
}

interface AladhanData {
  timings: Record<string, string>;
  date: {
    gregorian: { date: string; weekday: { en: string } };
    hijri: {
      day: string;
      month: { en: string; ar?: string; number: number };
      year: string;
      weekday: { en: string };
      holidays?: string[];
    };
  };
  meta?: { method?: { name?: string } };
}

interface GeocodeResult {
  id: number;
  name: string;
  latitude: number;
  longitude: number;
  country: string;
  admin1?: string;
}

interface NominatimAddress {
  city?: string;
  town?: string;
  village?: string;
  hamlet?: string;
  county?: string;
  state?: string;
  country?: string;
}

interface NominatimResponse {
  name?: string;
  address?: NominatimAddress;
}

async function reverseGeocode(lat: string, lng: string): Promise<string | null> {
  const url = `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&zoom=10&accept-language=en`;
  const res = await fetch(url, { headers: { "User-Agent": "firdam-app" } });
  if (!res.ok) return null;
  const json = (await res.json()) as NominatimResponse;
  const addr = json.address;
  if (!addr) return json.name ?? null;
  const city = addr.city ?? addr.town ?? addr.village ?? addr.hamlet ?? addr.county ?? json.name ?? null;
  const country = addr.country ?? null;
  if (city && country) return `${city}, ${country}`;
  return city ?? country ?? json.name ?? null;
}

/** Aladhan's calendar endpoint appends a zone, e.g. "05:12 (EDT)" — keep HH:MM. */
function clean(t: string | undefined): string {
  return (t ?? "").trim().split(" ")[0] ?? "";
}

function filterTimings(raw: Record<string, string>): PrayerTimings {
  return {
    Imsak: clean(raw.Imsak),
    Fajr: clean(raw.Fajr),
    Sunrise: clean(raw.Sunrise),
    Dhuhr: clean(raw.Dhuhr),
    Asr: clean(raw.Asr),
    Maghrib: clean(raw.Maghrib),
    Isha: clean(raw.Isha),
    Midnight: clean(raw.Midnight),
  };
}

function toDay(d: AladhanData) {
  return {
    timings: filterTimings(d.timings),
    gregorian: {
      date: d.date.gregorian.date,
      weekday: d.date.gregorian.weekday.en,
    },
    hijri: {
      day: d.date.hijri.day,
      month: d.date.hijri.month.en,
      monthAr: d.date.hijri.month.ar ?? null,
      monthNumber: d.date.hijri.month.number,
      year: d.date.hijri.year,
      weekday: d.date.hijri.weekday.en,
      holidays: d.date.hijri.holidays ?? [],
    },
    method: d.meta?.method?.name ?? null,
  };
}

/** Server time is UTC, so the client sends its own local date (DD-MM-YYYY). */
function todayDatePath(): string {
  const d = new Date();
  const dd = d.getUTCDate().toString().padStart(2, "0");
  const mm = (d.getUTCMonth() + 1).toString().padStart(2, "0");
  const yyyy = d.getUTCFullYear();
  return `${dd}-${mm}-${yyyy}`;
}

const VALID_METHODS = new Set([0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]);

function calcParams(url: URL): string {
  const method = Number(url.searchParams.get("method") ?? "2");
  const school = url.searchParams.get("school") === "1" ? 1 : 0;
  const m = VALID_METHODS.has(method) ? method : 2;
  return `method=${m}&school=${school}`;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const lat = url.searchParams.get("lat");
    const lng = url.searchParams.get("lng");
    const q = url.searchParams.get("q"); // city search query
    const reverse = url.searchParams.get("reverse") === "1";

    // Reverse geocode: coordinates -> "City, Country"
    if (reverse && lat && lng) {
      const label = await reverseGeocode(lat, lng);
      return new Response(
        JSON.stringify({ label }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // City search via Open-Meteo geocoding
    if (q) {
      const geoUrl = `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=8&language=en&format=json`;
      const geoRes = await fetch(geoUrl);
      if (!geoRes.ok) {
        return new Response(
          JSON.stringify({ error: "City search failed." }),
          { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const geoJson = (await geoRes.json()) as { results?: GeocodeResult[] };
      const places = (geoJson.results ?? []).map((r) => ({
        id: r.id,
        name: r.name,
        country: r.country,
        region: r.admin1 ?? "",
        latitude: r.latitude,
        longitude: r.longitude,
        label: `${r.name}${r.admin1 ? `, ${r.admin1}` : ""}, ${r.country}`,
      }));
      return new Response(JSON.stringify({ places }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Monthly timetable: ?lat&lng&month=10&year=2026 (Gregorian) or &hijriMonth=9&hijriYear=1448
    const month = url.searchParams.get("month");
    const year = url.searchParams.get("year");
    const hijriMonth = url.searchParams.get("hijriMonth");
    const hijriYear = url.searchParams.get("hijriYear");
    if (lat && lng && ((month && year) || (hijriMonth && hijriYear))) {
      const path = hijriMonth && hijriYear
        ? `hijriCalendar/${encodeURIComponent(hijriYear)}/${encodeURIComponent(hijriMonth)}`
        : `calendar/${encodeURIComponent(year!)}/${encodeURIComponent(month!)}`;
      const apiUrl = `https://api.aladhan.com/v1/${path}?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lng)}&${calcParams(url)}`;
      const res = await fetch(apiUrl);
      if (!res.ok) {
        return new Response(
          JSON.stringify({ error: `Upstream API error (${res.status})` }),
          { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const json = (await res.json()) as { data: AladhanData[] };
      return new Response(JSON.stringify({ days: json.data.map(toDay) }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Prayer times for one day by coordinates (?date=DD-MM-YYYY, defaults to today UTC)
    if (lat && lng) {
      const requested = url.searchParams.get("date");
      const datePath = requested && /^\d{2}-\d{2}-\d{4}$/.test(requested) ? requested : todayDatePath();
      const apiUrl = `https://api.aladhan.com/v1/timings/${datePath}?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lng)}&${calcParams(url)}`;
      const res = await fetch(apiUrl);
      if (!res.ok) {
        return new Response(
          JSON.stringify({ error: `Upstream API error (${res.status})` }),
          { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const json = (await res.json()) as { data: AladhanData };

      return new Response(JSON.stringify(toDay(json.data)), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(
      JSON.stringify({ error: "Provide lat+lng or q query parameter." }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
