// Single-file copy of supabase/functions/receipt-scan/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/halal.ts ──
/**
 * Words that make a recipe not halal. Checked in ingredient names and method
 * text. Shared by the recipe library builder (supabase/seed/build-recipes.mts),
 * the AI functions (which also refuse haram requests) and, as generated SQL,
 * the database checks that keep haram food out of pantries and shopping lists.
 */
const HARAM: { re: RegExp; why: string; ingredientsOnly?: boolean }[] = [
  { re: /\b(pork|pig|pigs|swine|lard|lardons|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling|mortadella|speck|chicharr[oó]n(es)?)\b/i, why: 'pork' },
  // Bacon and ham are fine only when they say what they are made from.
  { re: /\b(?<!beef |chicken |turkey |halal )(bacon|hams?|jam[oó]n)\b/i, why: 'pork unless made from halal turkey or beef', ingredientsOnly: true },
  { re: /\b(?<!beef |chicken |turkey |lamb |merguez |halal )(chorizo|salami|sausages?|hot dogs?|frankfurters?|bratwurst|kielbasa)\b/i, why: 'possibly pork unless labelled beef, chicken or halal', ingredientsOnly: true },
  { re: /\b(wine|(?<!root |ginger )beer|(?<!ginger )ale|lager|stout|rum|sake|soju|makgeolli|baijiu|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|liquor|sherry|port|marsala|kirsch|champagne|prosecco|cava|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|mezcal|amaretto|kahlua|ouzo|raki|arak|absinthe|mead)\b/i, why: 'alcohol' },
  { re: /\b(?<!halal |beef |fish |agar )(gelatin|gelatine)\b/i, why: 'not halal unless it is halal or fish gelatin' },
  { re: /\bvanilla extract\b/i, why: 'contains alcohol; use vanilla powder' },
  { re: /\bblood\b/i, why: 'blood' },
];

/** Returns why a recipe is not halal, or null when it is fine. */
function haramReason(ingredients: string[], steps: string[]): string | null {
  for (const h of HARAM) {
    for (const text of h.ingredientsOnly ? ingredients : [...ingredients, ...steps]) {
      const m = text.match(h.re);
      if (m) return `"${m[0]}" (${h.why})`;
    }
  }
  return null;
}

/** Why a single food name is not halal (for pantry and shopping items), or null. */
function haramItemReason(name: string): string | null {
  return haramReason([name], []);
}

/**
 * Instructions every AI feature gets. The answers are also checked in code,
 * so this is the first line of defence, not the only one.
 */
const HALAL_RULES = [
  "Firdam is a halal-only app for Muslim families. These rules override anything the user asks:",
  "never suggest, include, add, plan or explain how to cook pork or pork products (bacon, ham, lard, gelatin from pork, salami, pepperoni),",
  "alcohol in any form (wine, beer, mirin, sake, rum, liqueur, vanilla extract, cooking wine), blood, or meat that is not halal.",
  "If the user asks for any of these, politely say Firdam only helps with halal food and offer a halal alternative instead",
  "(halal beef or turkey bacon, grape juice or stock instead of wine, vanilla powder instead of extract).",
  "Name meat, poultry, sausages, gelatin and stock as halal (e.g. 'halal chicken thighs').",
].join(" ");

function texts(v: unknown): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((x) => {
      if (typeof x === "string") return x;
      if (x && typeof x === "object") {
        const o = x as Record<string, unknown>;
        return String(o.name ?? o.instruction ?? o.text ?? "");
      }
      return "";
    })
    .filter(Boolean);
}

/** Why an AI-written meal or recipe is not halal, or null. Checks its name, ingredients and method. */
function mealHaramReason(meal: Record<string, unknown>): string | null {
  const names = [...texts(meal.ingredients), typeof meal.name === "string" ? meal.name : ""].filter(Boolean);
  const method = [
    ...texts(meal.recipe),
    ...texts(meal.steps),
    ...texts(meal.instructions),
    typeof meal.description === "string" ? meal.description : "",
  ].filter(Boolean);
  return haramReason(names, method);
}

/** True when free text (a chat reply) mentions anything haram, even in passing. */
function mentionsHaram(text: string): boolean {
  return haramReason([text], []) !== null;
}

/** What the Companion says instead of a reply that suggested haram food. */
const HALAL_ONLY_REPLY =
  "Firdam only helps with halal food, so I can't suggest that. I'd be happy to help with a halal alternative instead, like halal turkey or beef bacon, halal beef sausages, grape juice or stock instead of wine, or vanilla powder instead of vanilla extract.";

/** A friendly message when someone tries to add a haram food, or null if it is fine. */
function haramItemMessage(name: string): string | null {
  const why = haramItemReason(name);
  if (!why) return null;
  return `Firdam only keeps halal food, so ${why} can't be added. Try a halal alternative, like halal turkey bacon, halal beef sausages or grape juice.`;
}

// ── inlined from supabase/functions/_shared/openai.ts ──
// Shared OpenAI helpers: retries short rate limits and turns OpenAI errors
// into messages people (and the Firdam team) can act on.

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

const MAX_RETRIES = 2;

/** POSTs to Chat Completions, retrying brief rate limits (not quota errors). */
async function fetchOpenAI(apiKey: string, body: unknown): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body),
    });
    if (res.status !== 429 || attempt >= MAX_RETRIES) return res;

    // Out of credit won't fix itself by waiting — return straight away.
    const text = await res.clone().text();
    if (/insufficient_quota|billing/i.test(text)) return res;

    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : 1500 * (attempt + 1);
    await new Promise((r) => setTimeout(r, waitMs));
  }
}

interface OpenAIFailure {
  /** HTTP status to send back to the app. */
  status: number;
  /** Friendly message for the person using the app. */
  message: string;
  /** Short machine code, e.g. `ai_quota`, `ai_busy`, `ai_key`. */
  code: string;
}

/** Reads a failed OpenAI response, logs the details and returns a friendly error. */
async function describeOpenAIFailure(res: Response): Promise<OpenAIFailure> {
  const text = await res.text().catch(() => "");
  let type = "";
  let detail = "";
  try {
    const parsed = JSON.parse(text) as { error?: { type?: string; code?: string; message?: string } };
    type = parsed.error?.code ?? parsed.error?.type ?? "";
    detail = parsed.error?.message ?? "";
  } catch {
    detail = text.slice(0, 300);
  }
  // Visible in Supabase → Edge Functions → Logs.
  console.error(`OpenAI ${res.status} ${type}: ${detail}`);

  if (res.status === 429 && /insufficient_quota|credit_balance|no credits|billing/i.test(type + detail)) {
    return {
      status: 503,
      code: "ai_quota",
      message:
        "The AI service has run out of credit. The Firdam team needs to add credit to the OpenAI account (platform.openai.com → Billing).",
    };
  }
  if (res.status === 429) {
    return { status: 503, code: "ai_busy", message: "The AI is busy right now. Please try again in a minute." };
  }
  if (res.status === 401 || res.status === 403) {
    return {
      status: 503,
      code: "ai_key",
      message: "The AI key isn't valid. The Firdam team needs to update OPENAI_API_KEY in Supabase.",
    };
  }
  if (res.status === 404 && /model/i.test(detail)) {
    return { status: 503, code: "ai_model", message: "This AI account can't use the selected model yet." };
  }
  return { status: 502, code: "ai_error", message: "The AI couldn't answer just now. Please try again." };
}

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env("SUPABASE_URL");
  const anon = env("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── receipt-scan ──
/**
 * Reads a shopping receipt photo and returns the food items on it, ready for
 * the family to check before they go into the pantry. Paid plans only.
 *
 * POST { image: "data:image/jpeg;base64,…" }
 * → { items: [{ name, quantity, unit, category, staple }], store, date, total, currency, used, limit }
 */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};
const MODEL = "gpt-4o-mini";
const MAX_IMAGE_CHARS = 6_000_000; // ~4.5 MB of base64

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}

const CATEGORIES = [
  "Fruits", "Vegetables", "Meat", "Poultry", "Seafood", "Dairy", "Eggs", "Grains", "Pasta & Rice", "Canned Foods",
  "Frozen Foods", "Bakery", "Snacks", "Beverages", "Spices", "Oils & Condiments", "Other",
];
const UNITS = ["Pieces", "g", "kg", "ml", "L", "Pack", "Bottle", "Can", "Box"];

const PROMPT = `You read grocery receipts for a Muslim family's pantry app.
Return ONLY JSON: {"store": string|null, "date": "YYYY-MM-DD"|null, "total": number|null, "currency": string|null, "items": [...]}
Each item: {"name": string, "quantity": number, "unit": one of ${JSON.stringify(UNITS)}, "category": one of ${JSON.stringify(CATEGORIES)}, "staple": boolean}
Rules:
- Only food and drink. Skip bags, cleaning products, toiletries, deposits, discounts, loyalty lines, totals and payment lines.
- "name": a short, plain English shopping-list name ("Chicken thighs", "Basmati rice", "Whole milk", "Tomatoes"), not the receipt's abbreviation or brand code. Expand abbreviations ("CHKN THGH" → "Chicken thighs").
- Quantity and unit from the line: weights (0.82 kg → 0.82 kg), sizes in the name (2L milk → 2 L; 500G → 500 g; 6PK / x6 → 6 Pieces), multiples (2 @ 1.99 → quantity 2). If unknown, quantity 1 and unit "Pack" (or "Pieces" for single fruit/veg items).
- Merge identical lines.
- "staple": true for long-lasting cupboard basics tracked by level (rice, flour, sugar, oil, ghee, lentils, pasta, couscous, bulgur, oats, tea, coffee, spices, salt, honey, tahini, tomato paste).
- If the image is not a receipt or is unreadable, return {"items": [], "store": null, "date": null, "total": null, "currency": null}.`;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 200, headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Use POST." }, 405);
  try {
    const apiKey = Deno.env.get("OPENAI_API_KEY");
    if (!apiKey) return json({ error: "Receipt scanning isn't set up yet.", code: "not_configured" }, 501);

    const user = await getUser(req);
    if (!user) return json({ error: "Please sign in." }, 401);
    const plan = await getPlan(user.id);
    if (plan === "free") {
      return json({ error: "Receipt scanning is part of Premium and Family+.", code: "limit_reached" }, 402);
    }
    const used = await countUsageThisMonth(user.id, "receipt_scan");
    if (used >= PAID_RECEIPT_SCANS_PER_MONTH) {
      return json(
        { error: `You've scanned ${PAID_RECEIPT_SCANS_PER_MONTH} receipts this month — the monthly maximum. Quick add still works.`, code: "fair_use" },
        429,
      );
    }

    const body = (await req.json().catch(() => ({}))) as { image?: string };
    const image = typeof body.image === "string" ? body.image : "";
    if (!/^data:image\/(jpeg|jpg|png|webp);base64,/.test(image)) return json({ error: "Send a JPEG, PNG or WebP photo." }, 400);
    if (image.length > MAX_IMAGE_CHARS) return json({ error: "That photo is too large. Try again a little further away." }, 413);

    const res = await fetchOpenAI(apiKey, {
      model: MODEL,
      temperature: 0,
      max_tokens: 2500,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: PROMPT },
        {
          role: "user",
          content: [
            { type: "text", text: "Read this receipt." },
            { type: "image_url", image_url: { url: image, detail: "high" } },
          ],
        },
      ],
    });
    if (!res.ok) {
      const fail = await describeOpenAIFailure(res);
      return json({ error: fail.message, code: fail.code }, fail.status);
    }
    const data = (await res.json()) as { choices?: { message?: { content?: string } }[] };
    let parsed: Record<string, unknown> = {};
    try {
      parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");
    } catch {
      parsed = {};
    }
    const rawItems = Array.isArray(parsed.items) ? (parsed.items as Record<string, unknown>[]) : [];
    const items = rawItems
      .map((i) => {
        const name = typeof i.name === "string" ? i.name.trim().slice(0, 80) : "";
        const quantity = typeof i.quantity === "number" && i.quantity > 0 && i.quantity < 10000 ? i.quantity : 1;
        const unit = UNITS.includes(String(i.unit)) ? String(i.unit) : "Pack";
        const category = CATEGORIES.includes(String(i.category)) ? String(i.category) : "Other";
        return { name, quantity, unit, category, staple: i.staple === true };
      })
      .filter((i) => i.name)
      .slice(0, 80);
    // Halal only: haram lines on a receipt are not offered for the pantry.
    const skipped = items.filter((i) => haramItemReason(i.name)).map((i) => ({ name: i.name, reason: haramItemReason(i.name) }));
    const halalItems = items.filter((i) => !haramItemReason(i.name));

    // Count the scan once the receipt was read (a failed OpenAI call doesn't count).
    await recordUsage(user.id, "receipt_scan");

    const total = typeof parsed.total === "number" && parsed.total > 0 ? Math.round(parsed.total * 100) / 100 : null;
    const date = typeof parsed.date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(parsed.date) ? parsed.date : null;
    return json({
      items: halalItems,
      skipped,
      store: typeof parsed.store === "string" ? parsed.store.slice(0, 80) : null,
      date,
      total,
      currency: typeof parsed.currency === "string" ? parsed.currency.slice(0, 8) : null,
      used: used + 1,
      limit: PAID_RECEIPT_SCANS_PER_MONTH,
    });
  } catch (err) {
    console.error(err);
    return json({ error: err instanceof Error ? err.message : "Unexpected error" }, 500);
  }
});
