// Single-file copy of supabase/functions/recipe-complete/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/allergens.ts ──
/**
 * Allergen and diet detection from ingredient names.
 *
 * Used by the Recipes filters and the meal planner so allergies are respected
 * even for recipes that have no allergen tags (e.g. family recipes users add).
 * Keep in sync with supabase/seed/recipe_tags.py, which tags the library.
 * Also used by the recipe-complete edge function to tag recipes it writes.
 */

interface AllergenRule {
  /** Name shown in the app. */
  name: string;
  /** Other words people use for the same allergy (matched case-insensitively). */
  aliases: string[];
  include: RegExp;
  /** Ingredients that look like a match but aren't (e.g. coconut milk for Dairy). */
  exclude?: RegExp;
}

const ALLERGEN_RULES: AllergenRule[] = [
  {
    name: 'Gluten',
    aliases: ['gluten', 'wheat', 'coeliac', 'celiac', 'barley', 'rye'],
    include:
      /\b(flour|bread|breadcrumbs?|brioche|baguettes?|croissants?|bagels?|sourdough|msemen|baghrir|pretzels?|waffles?|crumpets?|muffins?|panko|pitta?s?|naan|chapati|roti|paratha|flatbreads?|lepinja|tortillas?|wraps?|pasta|spaghetti|penne|fusilli|macaroni|fettuccine|tagliatelle|linguine|rigatoni|ravioli|tortellini|buns?|bread rolls?|granola|muesli|lasagne|lasagna|orzo|noodles?|vermicelli|couscous|bulgur|bulgh?ur|freekeh|frik|semolina|barley|wheat|rye|spelt|seitan|filo|phyllo|puff pastry|pastry|brik|warka|pizza dough|dough|soy sauce|kecap manis|teriyaki sauce|oyster sauce|hoisin|crackers?|biscuits?|cake|rusk|kataifi|kunafa|knafeh|malt|jareesh|harees|yufka)\b/,
    exclude:
      /\b(rice flour|glutinous rice flour|gluten-free|chickpea flour|gram flour|besan|corn ?flour|cornmeal|(white |yellow )?maize (flour|meal)|maize|almond flour|coconut flour|tapioca|cassava|teff|potato flour|buckwheat|rice noodles?|rice vermicelli|glass noodles|rice paper|corn tortillas?|tamari|coconut aminos|rice cakes?)\b/,
  },
  {
    name: 'Dairy',
    aliases: ['dairy', 'milk', 'lactose', 'cow milk'],
    include:
      /\b(milk|butter|ghee|cream|yogh?urt|labneh|cheese|paneer|feta|halloumi|mozzarella|parmesan|cheddar|ricotta|mascarpone|akkawi|nabulsi|jameed|kashk|kefir|buttermilk|whey|casein|custard|ice cream|khoa|khoya|condensed|evaporated|tzatziki|creme fraiche|crème fraîche|qishta|ashta)\b/,
    exclude:
      /\b(coconut milk|coconut cream|almond milk|oat milk|soy milk|soya milk|rice milk|peanut butter|almond butter|cashew butter|nut butter|shea butter|cocoa butter|cream of tartar|butter beans?|butterhead|dairy-free|vegan (butter|cheese|yogh?urt)|coconut yogh?urt)\b/,
  },
  {
    name: 'Eggs',
    aliases: ['egg', 'eggs'],
    include: /\b(eggs?|egg yolks?|egg whites?|mayonnaise|mayo|meringue|aioli)\b/,
    exclude: /\b(eggplants?|egg-free|vegan mayo)\b/,
  },
  {
    name: 'Tree nuts',
    aliases: ['tree nuts', 'tree nut', 'nuts', 'nut'],
    include:
      /\b(almonds?|walnuts?|pistachios?|cashews?|hazelnuts?|pecans?|pine nuts?|macadamias?|brazil nuts?|praline|marzipan|frangipane|nut butter|almond (flour|milk|butter|extract)|mixed nuts|nuts)\b/,
    exclude: /\b(nutmeg|coconut|doughnut|butternut|peanuts?|tiger nuts?|water chestnuts?)\b/,
  },
  {
    name: 'Peanuts',
    aliases: ['peanut', 'peanuts', 'groundnut', 'groundnuts'],
    include: /\b(peanuts?|groundnuts?|peanut butter|peanut oil|satay sauce)\b/,
  },
  {
    name: 'Sesame',
    aliases: ['sesame'],
    include: /\b(sesame|tahini|tahina|za'?atar|halva|halwa tahini|dukkah|gomasio)\b/,
  },
  {
    name: 'Fish',
    aliases: ['fish'],
    include:
      /\b(fish|salmon|tuna|cod|haddock|hake|pollock|tilapia|sea ?bass|branzino|bream|snapper|mackerel|sardines?|anchov(y|ies)|herring|trout|halibut|kingfish|grouper|carp|catfish|swordfish|whitebait|fish sauce|worcestershire|shito|bonito|dashi|maldive fish|dried fish)\b/,
    exclude: /\b(fish-free|vegan fish sauce)\b/,
  },
  {
    name: 'Shellfish',
    aliases: ['shellfish', 'crustaceans', 'molluscs', 'mollusks', 'seafood'],
    include:
      /\b(prawns?|shrimps?|crabs?|lobsters?|crayfish|langoustines?|mussels?|clams?|oysters?|scallops?|squid|calamari|octopus|cuttlefish|shrimp paste|belacan|laksa paste|shito|terasi|oyster sauce|dried shrimp)\b/,
  },
  {
    name: 'Soy',
    aliases: ['soy', 'soya', 'soybean', 'soybeans'],
    include: /\b(soy|soya|tofu|tempeh|edamame|miso|kecap manis|tamari|teriyaki sauce|soybeans?|hoisin)\b/,
  },
  {
    name: 'Mustard',
    aliases: ['mustard'],
    include: /\b(mustard)\b/,
  },
  {
    name: 'Celery',
    aliases: ['celery', 'celeriac'],
    include: /\b(celery|celeriac|stock cubes?|bouillon)\b/,
  },
];

const MEAT_RE =
  /\b(chicken|beef|lamb|mutton|goat|veal|turkey|duck|quail|camel|mince|minced meat|meat|sucuk|sujuk|beef chorizo|beef bacon|pastirma|basturma|liver|kidneys?|oxtail|bone broth|gelatin|gelatine|chicken stock|beef stock|lamb stock|stock cube|bouillon)\b/;
const MEAT_EXCLUDE = /\b(vegetable stock|vegetable bouillon|meat-free|plant-based|coconut meat)\b/;
const SEAFOOD_RULES = ALLERGEN_RULES.filter((r) => r.name === 'Fish' || r.name === 'Shellfish');

function normalize(s: string) {
  return s.toLowerCase().replace(/[’`]/g, "'").replace(/\s+/g, ' ').trim();
}

function matchesRule(rule: AllergenRule, ingredient: string): boolean {
  const n = normalize(ingredient);
  if (!rule.include.test(n)) return false;
  if (!rule.exclude) return true;
  // Excluded phrase only cancels the match if nothing else in the name matches.
  const stripped = n.replace(new RegExp(rule.exclude.source, 'g'), ' ');
  return rule.include.test(stripped);
}

/** Allergen names (from ALLERGEN_RULES) found in a list of ingredient names. */
function detectAllergens(ingredients: string[]): Set<string> {
  const found = new Set<string>();
  for (const rule of ALLERGEN_RULES) {
    if (ingredients.some((i) => matchesRule(rule, i))) found.add(rule.name);
  }
  return found;
}

/** Finds the rule for something a user typed or picked, e.g. "Milk" → Dairy, "Nuts" → Tree nuts. */
function ruleForAllergy(allergy: string): AllergenRule | undefined {
  const a = normalize(allergy);
  return ALLERGEN_RULES.find((r) => normalize(r.name) === a || r.aliases.includes(a));
}

function singular(word: string) {
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (word.endsWith('oes')) return word.slice(0, -2);
  if (word.length > 3 && word.endsWith('s') && !word.endsWith('ss')) return word.slice(0, -1);
  return word;
}

/**
 * True when a recipe is unsafe for someone with any of `allergies`.
 * Known allergens use the rules (plus the recipe's own tags); anything else the
 * user typed ("mushroom", "coriander") is matched against ingredient names.
 */
function conflictsWithAllergies(
  ingredients: string[],
  allergies: string[],
  taggedAllergens: string[] = []
): boolean {
  if (allergies.length === 0) return false;
  const detected = detectAllergens(ingredients);
  const tagged = new Set(taggedAllergens.map((t) => ruleForAllergy(t)?.name ?? normalize(t)));
  const names = ingredients.map(normalize);
  return allergies.some((allergy) => {
    const rule = ruleForAllergy(allergy);
    if (rule) return detected.has(rule.name) || tagged.has(rule.name);
    const word = singular(normalize(allergy));
    if (!word) return false;
    return tagged.has(normalize(allergy)) || names.some((n) => n.split(/[^a-z']+/).map(singular).join(' ').includes(word));
  });
}

type Diet = 'Vegetarian' | 'Vegan' | 'Pescatarian' | 'Gluten-free' | 'Dairy-free' | 'Low-carb' | 'High-protein' | 'Kid-friendly';

function hasMeat(ingredients: string[]): boolean {
  return ingredients.some((i) => {
    const n = normalize(i);
    return MEAT_RE.test(n) && !MEAT_EXCLUDE.test(n);
  });
}

function hasSeafood(ingredients: string[]): boolean {
  return ingredients.some((i) => SEAFOOD_RULES.some((r) => matchesRule(r, i)));
}

/**
 * True when a recipe suits a dietary preference. Nutrition-based diets use the
 * recipe's numbers; "Kid-friendly" relies on the recipe's tag.
 */
function fitsDiet(
  diet: string,
  recipe: { ingredients: string[]; tags?: string[]; protein?: number | null; carbs?: number | null }
): boolean {
  const tags = new Set((recipe.tags ?? []).map(normalize));
  const allergens = detectAllergens(recipe.ingredients);
  switch (normalize(diet)) {
    case 'vegetarian':
      return !hasMeat(recipe.ingredients) && !hasSeafood(recipe.ingredients);
    case 'vegan':
      return (
        !hasMeat(recipe.ingredients) &&
        !hasSeafood(recipe.ingredients) &&
        !allergens.has('Dairy') &&
        !allergens.has('Eggs') &&
        !recipe.ingredients.some((i) => /\bhoney\b/.test(normalize(i)))
      );
    case 'pescatarian':
      return !hasMeat(recipe.ingredients);
    case 'gluten-free':
      return !allergens.has('Gluten');
    case 'dairy-free':
      return !allergens.has('Dairy');
    case 'low-carb':
      return recipe.carbs != null ? recipe.carbs <= 25 : tags.has('low-carb');
    case 'high-protein':
      return recipe.protein != null ? recipe.protein >= 25 : tags.has('high-protein');
    case 'kid-friendly':
      return tags.has('kid-friendly');
    default:
      // Unknown preference from the database: trust a matching tag if there is one.
      return tags.size === 0 || tags.has(normalize(diet));
  }
}

/** Allergens offered in filters when the database list is empty. */
const DEFAULT_ALLERGENS = ALLERGEN_RULES.map((r) => r.name);

// ── inlined from supabase/functions/_shared/halal.ts ──
/**
 * Words that make a recipe not halal. Checked in ingredient names and method
 * text. Shared by the recipe library builder (supabase/seed/build-recipes.mts),
 * the AI functions (which also refuse haram requests) and, as generated SQL,
 * the database checks that keep haram food out of pantries and shopping lists.
 */
const HARAM: { re: RegExp; why: string; ingredientsOnly?: boolean }[] = [
  { re: /\b(pork|pig|pigs|swine|lard|lardons|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling|mortadella|speck|chicharr[oó]n(es)?)\b/i, why: 'pork' },
  // Bacon and ham are fine only when they say what they are made from.
  { re: /\b(?<!beef |chicken |turkey |halal )(bacon|hams?|jam[oó]n)\b/i, why: 'pork unless made from halal turkey or beef', ingredientsOnly: true },
  { re: /\b(?<!beef |chicken |turkey |lamb |merguez |halal )(chorizo|salami|sausages?|hot dogs?|frankfurters?|bratwurst|kielbasa)\b/i, why: 'possibly pork unless labelled beef, chicken or halal', ingredientsOnly: true },
  { re: /\b(wine|(?<!root |ginger )beer|(?<!ginger )ale|lager|stout|rum|sake|soju|makgeolli|baijiu|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|liquor|sherry|port|marsala|kirsch|champagne|prosecco|cava|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|mezcal|amaretto|kahlua|ouzo|raki|arak|absinthe|mead)\b/i, why: 'alcohol' },
  { re: /\b(?<!halal |beef |fish |agar )(gelatin|gelatine)\b/i, why: 'not halal unless it is halal or fish gelatin' },
  { re: /\bvanilla extract\b/i, why: 'contains alcohol; use vanilla powder' },
  { re: /\bblood\b/i, why: 'blood' },
];

/** Returns why a recipe is not halal, or null when it is fine. */
function haramReason(ingredients: string[], steps: string[]): string | null {
  for (const h of HARAM) {
    for (const text of h.ingredientsOnly ? ingredients : [...ingredients, ...steps]) {
      const m = text.match(h.re);
      if (m) return `"${m[0]}" (${h.why})`;
    }
  }
  return null;
}

/** Why a single food name is not halal (for pantry and shopping items), or null. */
function haramItemReason(name: string): string | null {
  return haramReason([name], []);
}

/**
 * Instructions every AI feature gets. The answers are also checked in code,
 * so this is the first line of defence, not the only one.
 */
const HALAL_RULES = [
  "Firdam is a halal-only app for Muslim families. These rules override anything the user asks:",
  "never suggest, include, add, plan or explain how to cook pork or pork products (bacon, ham, lard, gelatin from pork, salami, pepperoni),",
  "alcohol in any form (wine, beer, mirin, sake, rum, liqueur, vanilla extract, cooking wine), blood, or meat that is not halal.",
  "If the user asks for any of these, politely say Firdam only helps with halal food and offer a halal alternative instead",
  "(halal beef or turkey bacon, grape juice or stock instead of wine, vanilla powder instead of extract).",
  "Name meat, poultry, sausages, gelatin and stock as halal (e.g. 'halal chicken thighs').",
].join(" ");

function texts(v: unknown): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((x) => {
      if (typeof x === "string") return x;
      if (x && typeof x === "object") {
        const o = x as Record<string, unknown>;
        return String(o.name ?? o.instruction ?? o.text ?? "");
      }
      return "";
    })
    .filter(Boolean);
}

/** Why an AI-written meal or recipe is not halal, or null. Checks its name, ingredients and method. */
function mealHaramReason(meal: Record<string, unknown>): string | null {
  const names = [...texts(meal.ingredients), typeof meal.name === "string" ? meal.name : ""].filter(Boolean);
  const method = [
    ...texts(meal.recipe),
    ...texts(meal.steps),
    ...texts(meal.instructions),
    typeof meal.description === "string" ? meal.description : "",
  ].filter(Boolean);
  return haramReason(names, method);
}

/** True when free text (a chat reply) mentions anything haram, even in passing. */
function mentionsHaram(text: string): boolean {
  return haramReason([text], []) !== null;
}

/** What the Companion says instead of a reply that suggested haram food. */
const HALAL_ONLY_REPLY =
  "Firdam only helps with halal food, so I can't suggest that. I'd be happy to help with a halal alternative instead, like halal turkey or beef bacon, halal beef sausages, grape juice or stock instead of wine, or vanilla powder instead of vanilla extract.";

/** A friendly message when someone tries to add a haram food, or null if it is fine. */
function haramItemMessage(name: string): string | null {
  const why = haramItemReason(name);
  if (!why) return null;
  return `Firdam only keeps halal food, so ${why} can't be added. Try a halal alternative, like halal turkey bacon, halal beef sausages or grape juice.`;
}

// ── inlined from supabase/functions/_shared/openai.ts ──
// Shared OpenAI helpers: retries short rate limits and turns OpenAI errors
// into messages people (and the Firdam team) can act on.

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

const MAX_RETRIES = 2;

/** POSTs to Chat Completions, retrying brief rate limits (not quota errors). */
async function fetchOpenAI(apiKey: string, body: unknown): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body),
    });
    if (res.status !== 429 || attempt >= MAX_RETRIES) return res;

    // Out of credit won't fix itself by waiting — return straight away.
    const text = await res.clone().text();
    if (/insufficient_quota|billing/i.test(text)) return res;

    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : 1500 * (attempt + 1);
    await new Promise((r) => setTimeout(r, waitMs));
  }
}

interface OpenAIFailure {
  /** HTTP status to send back to the app. */
  status: number;
  /** Friendly message for the person using the app. */
  message: string;
  /** Short machine code, e.g. `ai_quota`, `ai_busy`, `ai_key`. */
  code: string;
}

/** Reads a failed OpenAI response, logs the details and returns a friendly error. */
async function describeOpenAIFailure(res: Response): Promise<OpenAIFailure> {
  const text = await res.text().catch(() => "");
  let type = "";
  let detail = "";
  try {
    const parsed = JSON.parse(text) as { error?: { type?: string; code?: string; message?: string } };
    type = parsed.error?.code ?? parsed.error?.type ?? "";
    detail = parsed.error?.message ?? "";
  } catch {
    detail = text.slice(0, 300);
  }
  // Visible in Supabase → Edge Functions → Logs.
  console.error(`OpenAI ${res.status} ${type}: ${detail}`);

  if (res.status === 429 && /insufficient_quota|credit_balance|no credits|billing/i.test(type + detail)) {
    return {
      status: 503,
      code: "ai_quota",
      message:
        "The AI service has run out of credit. The Firdam team needs to add credit to the OpenAI account (platform.openai.com → Billing).",
    };
  }
  if (res.status === 429) {
    return { status: 503, code: "ai_busy", message: "The AI is busy right now. Please try again in a minute." };
  }
  if (res.status === 401 || res.status === 403) {
    return {
      status: 503,
      code: "ai_key",
      message: "The AI key isn't valid. The Firdam team needs to update OPENAI_API_KEY in Supabase.",
    };
  }
  if (res.status === 404 && /model/i.test(detail)) {
    return { status: 503, code: "ai_model", message: "This AI account can't use the selected model yet." };
  }
  return { status: 502, code: "ai_error", message: "The AI couldn't answer just now. Please try again." };
}

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

function env_shared(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env_shared("SUPABASE_URL");
  const anon = env_shared("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env_shared("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── recipe-complete ──
/**
 * Admin tool: writes the ingredients and method for recipes that have a name,
 * description, cuisine, servings and times but nothing to cook from yet.
 * Every result passes the same halal check as the recipe library, and is
 * tagged with its allergens so "Safe for my family" can hide it.
 *
 *   GET  → { remaining }
 *   POST { limit?: 1–8, skip?: string[] } → { done, failed, remaining }
 *
 * The admin page calls POST repeatedly; a few recipes per call keeps each
 * call well inside the edge-function time limit.
 *
 * Secrets: OPENAI_API_KEY. Optional: RECIPE_MODEL (default gpt-4o-mini).
 */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}
function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

async function rpc<T>(fn: string, args: Record<string, unknown>): Promise<T> {
  const url = env("SUPABASE_URL")!;
  const key = env("SUPABASE_SERVICE_ROLE_KEY")!;
  const res = await fetch(`${url}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
    body: JSON.stringify(args),
  });
  if (!res.ok) throw new Error(`Database error ${res.status}: ${(await res.text()).slice(0, 200)}`);
  return (await res.json()) as T;
}

interface MissingRecipe {
  id: string;
  name: string;
  short_description: string | null;
  cuisine: string | null;
  meal_type: string | null;
  servings: number | null;
  prep_time_minutes: number | null;
  cook_time_minutes: number | null;
  calories: number | null;
}

interface Written {
  ingredients: { name: string; quantity: number | null; unit: string; optional?: boolean; notes?: string | null }[];
  steps: { instruction: string; minutes?: number | null }[];
  allergens: string[];
}

const UNITS: Record<string, string> = {
  g: "g", gram: "g", grams: "g", kg: "kg", ml: "ml", l: "l", litre: "l", liter: "l", litres: "l", liters: "l",
  tsp: "tsp", teaspoon: "tsp", teaspoons: "tsp", tbsp: "tbsp", tablespoon: "tbsp", tablespoons: "tbsp",
  cup: "cup", cups: "cup", piece: "pieces", pieces: "pieces", pcs: "pieces", whole: "pieces",
  clove: "cloves", cloves: "cloves", pinch: "pinch", handful: "handful", bunch: "bunch", "to taste": "to taste", "": "to taste",
};

const SYSTEM = [
  "You are a careful home-cooking recipe writer for Firdam, an app for Muslim families.",
  "Write the ingredients and method for the recipe described. Follow the name and description closely.",
  "Strictly halal: no pork or pork products, no alcohol in any form (no wine, mirin, beer, vanilla extract — use vanilla powder),",
  "no blood. Say 'halal' before meat, poultry, sausages, gelatin and stock cubes (e.g. 'halal beef mince', 'halal chicken stock cube').",
  "Ingredients: 5 to 15 items, amounts for the stated servings, metric. Units only from: g, kg, ml, l, tsp, tbsp, cup, pieces, cloves, pinch, handful, bunch, to taste.",
  "Ingredient names: lower case, plain and shoppable ('basmati rice', 'red onion', 'ground cumin'); preparation goes in notes ('finely chopped').",
  "Use 'to taste' with quantity null only for salt, pepper and similar seasonings.",
  "Allergies matter: name every ingredient so its allergens are obvious. Don't use ready-made mixes or sauces that hide them",
  "(write 'pine nuts' and 'parmesan' instead of 'pesto'; 'shrimp paste' not 'curry paste'; 'wheat flour' not 'flour mix').",
  "Use only what the dish really needs: no optional nuts, eggs or dairy added for garnish.",
  `List the allergens the recipe contains, using only these names: ${ALLERGEN_RULES.map((r) => r.name).join(", ")}.`,
  "Method: 4 to 9 clear steps in plain English, each one or two sentences, with times and heat where useful.",
  "Total time should roughly match the prep and cook minutes given.",
  'Reply with JSON only: {"ingredients":[{"name":"","quantity":0,"unit":"","optional":false,"notes":""}],"steps":[{"instruction":"","minutes":0}],"allergens":[""]}',
].join(" ");

function describe(r: MissingRecipe): string {
  return [
    `Recipe: ${r.name}`,
    r.short_description ? `Description: ${r.short_description}` : "",
    r.cuisine ? `Cuisine: ${r.cuisine}` : "",
    r.meal_type ? `Meal: ${r.meal_type}` : "",
    `Servings: ${r.servings ?? 4}`,
    r.prep_time_minutes != null ? `Prep: ${r.prep_time_minutes} min` : "",
    r.cook_time_minutes != null ? `Cook: ${r.cook_time_minutes} min` : "",
    r.calories != null ? `About ${r.calories} kcal per serving` : "",
  ].filter(Boolean).join("\n");
}

function clean(raw: unknown): Written | string {
  const w = raw as Partial<Written> | null;
  if (!w || !Array.isArray(w.ingredients) || !Array.isArray(w.steps)) return "the reply was not a recipe";
  const ingredients = w.ingredients
    .map((i) => {
      const unit = UNITS[String(i?.unit ?? "").trim().toLowerCase()] ?? "pieces";
      const q = Number(i?.quantity);
      return {
        name: String(i?.name ?? "").trim().toLowerCase().replace(/\s+/g, " "),
        quantity: unit === "to taste" || !Number.isFinite(q) || q <= 0 ? null : Math.round(q * 100) / 100,
        unit,
        optional: !!i?.optional,
        notes: i?.notes ? String(i.notes).trim().slice(0, 120) : null,
      };
    })
    .filter((i) => i.name && i.name.length <= 80);
  const steps = w.steps
    .map((s) => ({ instruction: String(s?.instruction ?? "").trim(), minutes: Number.isFinite(Number(s?.minutes)) && Number(s?.minutes) > 0 ? Math.round(Number(s?.minutes)) : null }))
    .filter((s) => s.instruction.length >= 10);
  if (ingredients.length < 3) return "too few ingredients";
  if (steps.length < 3) return "too few steps";
  const known = new Map(ALLERGEN_RULES.map((r) => [r.name.toLowerCase(), r.name]));
  const declared = (Array.isArray(w.allergens) ? w.allergens : [])
    .map((a) => known.get(String(a ?? "").trim().toLowerCase()))
    .filter((a): a is string => !!a);
  return { ingredients: ingredients.slice(0, 18), steps: steps.slice(0, 12), allergens: declared };
}

async function write(r: MissingRecipe, apiKey: string, model: string, note?: string): Promise<Written | string> {
  const res = await fetchOpenAI(apiKey, {
    model,
    temperature: 0.4,
    max_tokens: 1600,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: describe(r) + (note ? `\n\nImportant: ${note}` : "") },
    ],
  });
  if (!res.ok) {
    const f = await describeOpenAIFailure(res);
    throw Object.assign(new Error(f.message), { status: f.status });
  }
  const data = await res.json();
  const text = data?.choices?.[0]?.message?.content ?? "";
  try {
    return clean(JSON.parse(text));
  } catch {
    return "the reply was not valid JSON";
  }
}

async function complete(r: MissingRecipe, apiKey: string, model: string): Promise<{ ok: true; ingredients: number; steps: number; allergens: string[] } | { ok: false; reason: string }> {
  let result = await write(r, apiKey, model);
  for (let attempt = 0; attempt < 2; attempt++) {
    if (typeof result === "string") {
      result = await write(r, apiKey, model, `Your last answer had a problem: ${result}. Follow the format exactly.`);
      continue;
    }
    const reason = haramReason(result.ingredients.map((i) => i.name), result.steps.map((s) => s.instruction));
    if (!reason) break;
    result = await write(r, apiKey, model, `Your last answer was not halal: ${reason}. Use a halal alternative.`);
  }
  if (typeof result === "string") return { ok: false, reason: result };
  const stillHaram = haramReason(result.ingredients.map((i) => i.name), result.steps.map((s) => s.instruction));
  if (stillHaram) return { ok: false, reason: `not halal: ${stillHaram}` };

  // Tag what the chef declared and what our own rules find in the ingredient names.
  const found = new Set([...result.allergens, ...detectAllergens(result.ingredients.map((i) => i.name))]);
  const allergens = ALLERGEN_RULES.filter((rule) => found.has(rule.name)).map((rule) => [rule.name.toLowerCase(), ...rule.aliases]);
  const added = await rpc<number>("complete_recipe", { target: r.id, items: result.ingredients, steps: result.steps, allergens });
  return { ok: true, ingredients: added, steps: result.steps.length, allergens: [...found] };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const user = await getUser(req);
    if (!user || !(await isAdminUser(user.id))) return json({ error: "Only Firdam admins can use this tool." }, 403);

    if (req.method === "GET") {
      return json({ remaining: await rpc<number>("count_recipes_missing_ingredients", {}) });
    }
    if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

    const apiKey = env("OPENAI_API_KEY");
    if (!apiKey) return json({ error: "OPENAI_API_KEY is not set in Supabase → Edge Functions → Secrets." }, 501);
    const model = env("RECIPE_MODEL") ?? "gpt-4o-mini";

    const body = (await req.json().catch(() => ({}))) as { limit?: number; skip?: string[] };
    const limit = Math.min(8, Math.max(1, Number(body.limit) || 4));
    const skip = Array.isArray(body.skip) ? body.skip.filter((s) => /^[0-9a-f-]{36}$/i.test(s)).slice(0, 500) : [];
    const batch = await rpc<MissingRecipe[]>("recipes_missing_ingredients", { max_rows: limit, skip_ids: skip });

    const results = await Promise.all(
      batch.map(async (r) => {
        try {
          return { id: r.id, name: r.name, ...(await complete(r, apiKey, model)) };
        } catch (e) {
          const status = (e as { status?: number }).status;
          // Out of OpenAI credit or a bad key: stop the whole run, not just this recipe.
          if (status === 402 || status === 401 || status === 503) throw e;
          return { id: r.id, name: r.name, ok: false as const, reason: e instanceof Error ? e.message : "unknown error" };
        }
      })
    );

    return json({
      done: results.filter((r) => r.ok),
      failed: results.filter((r) => !r.ok),
      remaining: await rpc<number>("count_recipes_missing_ingredients", {}),
    });
  } catch (e) {
    const status = (e as { status?: number }).status ?? 500;
    return json({ error: e instanceof Error ? e.message : "Something went wrong" }, status);
  }
});
