// Single-file copy of supabase/functions/recipe-complete/index.ts for deploying from the
// Supabase dashboard. Generated by supabase/build-dashboard-functions.mjs — do not edit.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// ── inlined from supabase/functions/_shared/halal.ts ──
/**
 * Words that make a recipe not halal. Checked in ingredient names and method
 * text. Shared by the recipe library builder (supabase/seed/build-recipes.mts)
 * and the recipe-complete function.
 */
const HARAM: { re: RegExp; why: string; ingredientsOnly?: boolean }[] = [
  { re: /\b(pork|bacon|ham|lard|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling)\b/i, why: 'pork' },
  { re: /\b(?<!beef |chicken |halal )(chorizo|salami|sausages?)\b/i, why: 'possibly pork (say beef/chicken/halal)', ingredientsOnly: true },
  { re: /\b(wine|beer|ale|lager|rum|sake|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|sherry|port|marsala|kirsch|champagne|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|amaretto|kahlua)\b/i, why: 'alcohol' },
  { re: /\b(?<!halal |beef |fish |agar )(gelatin|gelatine)\b/i, why: 'gelatin (say halal gelatin)' },
  { re: /\bvanilla extract\b/i, why: 'vanilla extract contains alcohol (use vanilla powder)' },
  { re: /\bblood\b/i, why: 'blood' },
];

/** Returns why a recipe is not halal, or null when it is fine. */
function haramReason(ingredients: string[], steps: string[]): string | null {
  for (const h of HARAM) {
    for (const text of h.ingredientsOnly ? ingredients : [...ingredients, ...steps]) {
      const m = text.match(h.re);
      if (m) return `"${m[0]}" (${h.why})`;
    }
  }
  return null;
}

// ── inlined from supabase/functions/_shared/openai.ts ──
// Shared OpenAI helpers: retries short rate limits and turns OpenAI errors
// into messages people (and the Firdam team) can act on.

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

const MAX_RETRIES = 2;

/** POSTs to Chat Completions, retrying brief rate limits (not quota errors). */
async function fetchOpenAI(apiKey: string, body: unknown): Promise<Response> {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(OPENAI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body),
    });
    if (res.status !== 429 || attempt >= MAX_RETRIES) return res;

    // Out of credit won't fix itself by waiting — return straight away.
    const text = await res.clone().text();
    if (/insufficient_quota|billing/i.test(text)) return res;

    const retryAfter = Number(res.headers.get("retry-after"));
    const waitMs = Number.isFinite(retryAfter) && retryAfter > 0 ? Math.min(retryAfter * 1000, 8000) : 1500 * (attempt + 1);
    await new Promise((r) => setTimeout(r, waitMs));
  }
}

interface OpenAIFailure {
  /** HTTP status to send back to the app. */
  status: number;
  /** Friendly message for the person using the app. */
  message: string;
  /** Short machine code, e.g. `ai_quota`, `ai_busy`, `ai_key`. */
  code: string;
}

/** Reads a failed OpenAI response, logs the details and returns a friendly error. */
async function describeOpenAIFailure(res: Response): Promise<OpenAIFailure> {
  const text = await res.text().catch(() => "");
  let type = "";
  let detail = "";
  try {
    const parsed = JSON.parse(text) as { error?: { type?: string; code?: string; message?: string } };
    type = parsed.error?.code ?? parsed.error?.type ?? "";
    detail = parsed.error?.message ?? "";
  } catch {
    detail = text.slice(0, 300);
  }
  // Visible in Supabase → Edge Functions → Logs.
  console.error(`OpenAI ${res.status} ${type}: ${detail}`);

  if (res.status === 429 && /insufficient_quota/.test(type + detail)) {
    return {
      status: 503,
      code: "ai_quota",
      message:
        "The AI service has run out of credit. The Firdam team needs to add credit to the OpenAI account (platform.openai.com → Billing).",
    };
  }
  if (res.status === 429) {
    return { status: 503, code: "ai_busy", message: "The AI is busy right now. Please try again in a minute." };
  }
  if (res.status === 401 || res.status === 403) {
    return {
      status: 503,
      code: "ai_key",
      message: "The AI key isn't valid. The Firdam team needs to update OPENAI_API_KEY in Supabase.",
    };
  }
  if (res.status === 404 && /model/i.test(detail)) {
    return { status: 503, code: "ai_model", message: "This AI account can't use the selected model yet." };
  }
  return { status: 502, code: "ai_error", message: "The AI couldn't answer just now. Please try again." };
}

// ── inlined from supabase/functions/_shared/plan.ts ──
/**
 * Shared helpers for enforcing plan limits inside edge functions.
 * Uses the Supabase REST API with the service role (provided by Supabase).
 */

// Keep in sync with lib/plan/plan.ts. Each Companion message costs roughly
// $0.001–0.002 in OpenAI fees, an AI meal plan roughly $0.003–0.005.
const FREE_AI_PLANS_PER_MONTH = 1;
// The Companion chat is a paid feature; Free users get pantry matching (no AI) instead.
const FREE_COMPANION_MESSAGES_PER_MONTH = 0;
// Fair-use caps for paid plans, so one account can't run up a large bill.
// About two AI plans a week (a plan covers 3, 5 or 7 days); regenerating counts as a new plan.
const PAID_AI_PLANS_PER_MONTH = 8;
// Receipt scans (paid plans only): about $0.01 each in OpenAI fees.
const PAID_RECEIPT_SCANS_PER_MONTH = 30;
const PAID_COMPANION_MESSAGES_PER_DAY = 20;

function env_shared(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

interface AuthUser {
  id: string;
  email?: string;
}

async function getUser(req: Request): Promise<AuthUser | null> {
  const auth = req.headers.get("Authorization");
  const url = env_shared("SUPABASE_URL");
  const anon = env_shared("SUPABASE_ANON_KEY");
  if (!auth || !url || !anon) return null;
  const res = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } });
  if (!res.ok) return null;
  return (await res.json()) as AuthUser;
}

function serviceHeaders(): Record<string, string> | null {
  const service = env_shared("SUPABASE_SERVICE_ROLE_KEY");
  if (!service) return null;
  return { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json" };
}

async function getPlan(userId: string): Promise<"free" | "premium" | "family"> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return "free";
  const res = await fetch(
    `${url}/rest/v1/subscriptions?user_id=eq.${encodeURIComponent(userId)}&select=plan,status,current_period_end`,
    { headers },
  );
  if (!res.ok) return "free";
  const rows = (await res.json()) as { plan: string; status: string; current_period_end: string | null }[];
  const sub = rows[0];
  if (!sub) return "free";
  const live = ["active", "trialing", "past_due"].includes(sub.status);
  const notExpired = !sub.current_period_end || new Date(sub.current_period_end) > new Date();
  if (!live || !notExpired) return "free";
  return sub.plan === "family" ? "family" : sub.plan === "premium" ? "premium" : "free";
}

function countUsageThisMonth(userId: string, kind: string): Promise<number> {
  const now = new Date();
  return countUsageSince(userId, kind, new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString());
}

/** Usage in the last 24 hours (a rolling "day" that ignores time zones). */
function countUsageToday(userId: string, kind: string): Promise<number> {
  return countUsageSince(userId, kind, new Date(Date.now() - 24 * 3600_000).toISOString());
}

async function countUsageSince(userId: string, kind: string, since: string): Promise<number> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return 0;
  const res = await fetch(
    `${url}/rest/v1/ai_usage?user_id=eq.${encodeURIComponent(userId)}&kind=eq.${encodeURIComponent(kind)}&created_at=gte.${encodeURIComponent(since)}&select=id`,
    { headers: { ...headers, Prefer: "count=exact", Range: "0-0" } },
  );
  const range = res.headers.get("content-range"); // e.g. "0-0/3" or "*/0"
  const total = range?.split("/")[1];
  return total && total !== "*" ? Number(total) : 0;
}

async function recordUsage(userId: string, kind: string): Promise<void> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return;
  await fetch(`${url}/rest/v1/ai_usage`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify({ user_id: userId, kind }),
  });
}

/** True when the user is listed in `app_admins`. */
async function isAdminUser(userId: string): Promise<boolean> {
  const url = env_shared("SUPABASE_URL");
  const headers = serviceHeaders();
  if (!url || !headers) return false;
  const res = await fetch(`${url}/rest/v1/app_admins?user_id=eq.${encodeURIComponent(userId)}&select=user_id`, {
    headers,
  });
  if (!res.ok) return false;
  return ((await res.json()) as unknown[]).length > 0;
}

// ── recipe-complete ──
/**
 * Admin tool: writes the ingredients and method for recipes that have a name,
 * description, cuisine, servings and times but nothing to cook from yet.
 * Every result passes the same halal check as the recipe library.
 *
 *   GET  → { remaining }
 *   POST { limit?: 1–8, skip?: string[] } → { done, failed, remaining }
 *
 * The admin page calls POST repeatedly; a few recipes per call keeps each
 * call well inside the edge-function time limit.
 *
 * Secrets: OPENAI_API_KEY. Optional: RECIPE_MODEL (default gpt-4o-mini).
 */

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });
}
function env(name: string): string | undefined {
  const v = Deno.env.get(name);
  return v && v.trim() ? v.trim() : undefined;
}

async function rpc<T>(fn: string, args: Record<string, unknown>): Promise<T> {
  const url = env("SUPABASE_URL")!;
  const key = env("SUPABASE_SERVICE_ROLE_KEY")!;
  const res = await fetch(`${url}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
    body: JSON.stringify(args),
  });
  if (!res.ok) throw new Error(`Database error ${res.status}: ${(await res.text()).slice(0, 200)}`);
  return (await res.json()) as T;
}

interface MissingRecipe {
  id: string;
  name: string;
  short_description: string | null;
  cuisine: string | null;
  meal_type: string | null;
  servings: number | null;
  prep_time_minutes: number | null;
  cook_time_minutes: number | null;
  calories: number | null;
}

interface Written {
  ingredients: { name: string; quantity: number | null; unit: string; optional?: boolean; notes?: string | null }[];
  steps: { instruction: string; minutes?: number | null }[];
}

const UNITS: Record<string, string> = {
  g: "g", gram: "g", grams: "g", kg: "kg", ml: "ml", l: "l", litre: "l", liter: "l", litres: "l", liters: "l",
  tsp: "tsp", teaspoon: "tsp", teaspoons: "tsp", tbsp: "tbsp", tablespoon: "tbsp", tablespoons: "tbsp",
  cup: "cup", cups: "cup", piece: "pieces", pieces: "pieces", pcs: "pieces", whole: "pieces",
  clove: "cloves", cloves: "cloves", pinch: "pinch", handful: "handful", bunch: "bunch", "to taste": "to taste", "": "to taste",
};

const SYSTEM = [
  "You are a careful home-cooking recipe writer for Firdam, an app for Muslim families.",
  "Write the ingredients and method for the recipe described. Follow the name and description closely.",
  "Strictly halal: no pork or pork products, no alcohol in any form (no wine, mirin, beer, vanilla extract — use vanilla powder),",
  "no blood. Say 'halal' before meat, poultry, sausages, gelatin and stock cubes (e.g. 'halal beef mince', 'halal chicken stock cube').",
  "Ingredients: 5 to 15 items, amounts for the stated servings, metric. Units only from: g, kg, ml, l, tsp, tbsp, cup, pieces, cloves, pinch, handful, bunch, to taste.",
  "Ingredient names: lower case, plain and shoppable ('basmati rice', 'red onion', 'ground cumin'); preparation goes in notes ('finely chopped').",
  "Use 'to taste' with quantity null only for salt, pepper and similar seasonings.",
  "Method: 4 to 9 clear steps in plain English, each one or two sentences, with times and heat where useful.",
  "Total time should roughly match the prep and cook minutes given.",
  'Reply with JSON only: {"ingredients":[{"name":"","quantity":0,"unit":"","optional":false,"notes":""}],"steps":[{"instruction":"","minutes":0}]}',
].join(" ");

function describe(r: MissingRecipe): string {
  return [
    `Recipe: ${r.name}`,
    r.short_description ? `Description: ${r.short_description}` : "",
    r.cuisine ? `Cuisine: ${r.cuisine}` : "",
    r.meal_type ? `Meal: ${r.meal_type}` : "",
    `Servings: ${r.servings ?? 4}`,
    r.prep_time_minutes != null ? `Prep: ${r.prep_time_minutes} min` : "",
    r.cook_time_minutes != null ? `Cook: ${r.cook_time_minutes} min` : "",
    r.calories != null ? `About ${r.calories} kcal per serving` : "",
  ].filter(Boolean).join("\n");
}

function clean(raw: unknown): Written | string {
  const w = raw as Partial<Written> | null;
  if (!w || !Array.isArray(w.ingredients) || !Array.isArray(w.steps)) return "the reply was not a recipe";
  const ingredients = w.ingredients
    .map((i) => {
      const unit = UNITS[String(i?.unit ?? "").trim().toLowerCase()] ?? "pieces";
      const q = Number(i?.quantity);
      return {
        name: String(i?.name ?? "").trim().toLowerCase().replace(/\s+/g, " "),
        quantity: unit === "to taste" || !Number.isFinite(q) || q <= 0 ? null : Math.round(q * 100) / 100,
        unit,
        optional: !!i?.optional,
        notes: i?.notes ? String(i.notes).trim().slice(0, 120) : null,
      };
    })
    .filter((i) => i.name && i.name.length <= 80);
  const steps = w.steps
    .map((s) => ({ instruction: String(s?.instruction ?? "").trim(), minutes: Number.isFinite(Number(s?.minutes)) && Number(s?.minutes) > 0 ? Math.round(Number(s?.minutes)) : null }))
    .filter((s) => s.instruction.length >= 10);
  if (ingredients.length < 3) return "too few ingredients";
  if (steps.length < 3) return "too few steps";
  return { ingredients: ingredients.slice(0, 18), steps: steps.slice(0, 12) };
}

async function write(r: MissingRecipe, apiKey: string, model: string, note?: string): Promise<Written | string> {
  const res = await fetchOpenAI(apiKey, {
    model,
    temperature: 0.4,
    max_tokens: 1600,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: describe(r) + (note ? `\n\nImportant: ${note}` : "") },
    ],
  });
  if (!res.ok) {
    const f = await describeOpenAIFailure(res);
    throw Object.assign(new Error(f.message), { status: f.status });
  }
  const data = await res.json();
  const text = data?.choices?.[0]?.message?.content ?? "";
  try {
    return clean(JSON.parse(text));
  } catch {
    return "the reply was not valid JSON";
  }
}

async function complete(r: MissingRecipe, apiKey: string, model: string): Promise<{ ok: true; ingredients: number; steps: number } | { ok: false; reason: string }> {
  let result = await write(r, apiKey, model);
  for (let attempt = 0; attempt < 2; attempt++) {
    if (typeof result === "string") {
      result = await write(r, apiKey, model, `Your last answer had a problem: ${result}. Follow the format exactly.`);
      continue;
    }
    const reason = haramReason(result.ingredients.map((i) => i.name), result.steps.map((s) => s.instruction));
    if (!reason) break;
    result = await write(r, apiKey, model, `Your last answer was not halal: ${reason}. Use a halal alternative.`);
  }
  if (typeof result === "string") return { ok: false, reason: result };
  const stillHaram = haramReason(result.ingredients.map((i) => i.name), result.steps.map((s) => s.instruction));
  if (stillHaram) return { ok: false, reason: `not halal: ${stillHaram}` };

  const added = await rpc<number>("complete_recipe", { target: r.id, items: result.ingredients, steps: result.steps });
  return { ok: true, ingredients: added, steps: result.steps.length };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const user = await getUser(req);
    if (!user || !(await isAdminUser(user.id))) return json({ error: "Only Firdam admins can use this tool." }, 403);

    if (req.method === "GET") {
      return json({ remaining: await rpc<number>("count_recipes_missing_ingredients", {}) });
    }
    if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

    const apiKey = env("OPENAI_API_KEY");
    if (!apiKey) return json({ error: "OPENAI_API_KEY is not set in Supabase → Edge Functions → Secrets." }, 501);
    const model = env("RECIPE_MODEL") ?? "gpt-4o-mini";

    const body = (await req.json().catch(() => ({}))) as { limit?: number; skip?: string[] };
    const limit = Math.min(8, Math.max(1, Number(body.limit) || 4));
    const skip = Array.isArray(body.skip) ? body.skip.filter((s) => /^[0-9a-f-]{36}$/i.test(s)).slice(0, 500) : [];
    const batch = await rpc<MissingRecipe[]>("recipes_missing_ingredients", { max_rows: limit, skip_ids: skip });

    const results = await Promise.all(
      batch.map(async (r) => {
        try {
          return { id: r.id, name: r.name, ...(await complete(r, apiKey, model)) };
        } catch (e) {
          const status = (e as { status?: number }).status;
          // Out of OpenAI credit or a bad key: stop the whole run, not just this recipe.
          if (status === 402 || status === 401 || status === 503) throw e;
          return { id: r.id, name: r.name, ok: false as const, reason: e instanceof Error ? e.message : "unknown error" };
        }
      })
    );

    return json({
      done: results.filter((r) => r.ok),
      failed: results.filter((r) => !r.ok),
      remaining: await rpc<number>("count_recipes_missing_ingredients", {}),
    });
  } catch (e) {
    const status = (e as { status?: number }).status ?? 500;
    return json({ error: e instanceof Error ? e.message : "Something went wrong" }, status);
  }
});
