/**
 * Writes the halal and allergen rules (supabase/functions/_shared/halal.ts and
 * allergens.ts) as Postgres functions, so recipes saved straight into the
 * database get exactly the same checks as the app and the recipe library.
 *
 *   node --experimental-strip-types supabase/seed/build-recipe-checks.mts
 *
 * Writes supabase/migrations/20261011120000_recipe_checks.sql. CI checks it is
 * up to date, so edit the rules, then run this again.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ALLERGEN_RULES } from '../functions/_shared/allergens.ts';
import { HARAM } from '../functions/_shared/halal.ts';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', 'migrations', '20261011120000_recipe_checks.sql');

/** JS regex source → Postgres ARE: \b is \y there. */
const pg = (re: RegExp) => re.source.replace(/\\b/g, '\\y');
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

const haramCases = (forMethod: boolean) =>
  HARAM.filter((h) => !(forMethod && h.ingredientsOnly))
    .map(
      (h) => `    IF txt ~* ${lit(pg(h.re))} THEN
      RETURN substring(txt from ${lit(`(?i)(${pg(h.re)})`)}) || ' (' || ${lit(h.why)} || ')';
    END IF;`
    )
    .join('\n');

const allergenCases = ALLERGEN_RULES.map((r) => {
  const inc = lit(pg(r.include));
  const test = r.exclude
    ? `regexp_replace(n, ${lit(pg(r.exclude))}, ' ', 'g') ~ ${inc}`
    : `n ~ ${inc}`;
  return `      IF ${test} THEN found := array_append(found, ${lit(r.name)}); END IF;`;
}).join('\n');

const aliasRows = ALLERGEN_RULES.map(
  (r) => `    (${lit(r.name)}, ARRAY[${[r.name.toLowerCase(), ...r.aliases].map(lit).join(', ')}])`
).join(',\n');

const sql = `-- GENERATED by supabase/seed/build-recipe-checks.mts from the halal and
-- allergen rules the app uses. Do not edit by hand. Re-runnable.

-- Why a recipe is not halal, or null. Same rules as supabase/functions/_shared/halal.ts.
CREATE OR REPLACE FUNCTION public.recipe_haram_reason(ingredients text[], steps text[])
RETURNS text LANGUAGE plpgsql IMMUTABLE SET search_path = public AS $$
DECLARE
  txt text;
BEGIN
  FOREACH txt IN ARRAY coalesce(ingredients, '{}') LOOP
${haramCases(false)}
  END LOOP;
  -- Method text: the ingredient-only rules ("sausages") are skipped.
  FOREACH txt IN ARRAY coalesce(steps, '{}') LOOP
${haramCases(true)}
  END LOOP;
  RETURN NULL;
END;
$$;

-- Allergen names found in ingredient names. Same rules as supabase/functions/_shared/allergens.ts.
CREATE OR REPLACE FUNCTION public.recipe_allergen_names(ingredients text[])
RETURNS text[] LANGUAGE plpgsql IMMUTABLE SET search_path = public AS $$
DECLARE
  raw text;
  n text;
  found text[] := '{}';
BEGIN
  FOREACH raw IN ARRAY coalesce(ingredients, '{}') LOOP
    n := trim(regexp_replace(regexp_replace(lower(raw), '[’\`]', '''', 'g'), '\\s+', ' ', 'g'));
${allergenCases}
  END LOOP;
  RETURN ARRAY(SELECT DISTINCT unnest(found) ORDER BY 1);
END;
$$;

-- Saves many recipes at once: each one is checked for halal, its allergens are
-- tagged (from the rules plus any listed), then it is saved with complete_recipe.
--   batch: [{ "id": "…", "items": [...], "steps": [...], "allergens": ["Dairy"] }]
-- Returns { "saved": n, "skipped": [{ "id", "reason" }] }.
CREATE OR REPLACE FUNCTION public.complete_recipes_batch(batch jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r jsonb;
  names text[];
  method text[];
  why text;
  tags text[];
  candidates jsonb;
  saved integer := 0;
  skipped jsonb := '[]';
BEGIN
  FOR r IN SELECT * FROM jsonb_array_elements(batch) LOOP
    names := ARRAY(SELECT lower(x ->> 'name') FROM jsonb_array_elements(r -> 'items') x);
    method := ARRAY(SELECT x ->> 'instruction' FROM jsonb_array_elements(r -> 'steps') x);
    why := public.recipe_haram_reason(names, method);
    IF why IS NOT NULL THEN
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'not halal: ' || why);
      CONTINUE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.recipes WHERE id = (r ->> 'id')::uuid) THEN
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'recipe not found');
      CONTINUE;
    END IF;
    tags := public.recipe_allergen_names(names)
      || ARRAY(SELECT jsonb_array_elements_text(coalesce(r -> 'allergens', '[]')));
    SELECT coalesce(jsonb_agg(to_jsonb(a.names)), '[]') INTO candidates
      FROM (VALUES
${aliasRows}
      ) AS a(rule, names)
      WHERE lower(a.rule) IN (SELECT lower(t) FROM unnest(tags) t);
    IF public.complete_recipe((r ->> 'id')::uuid, r -> 'items', r -> 'steps', candidates) > 0 THEN
      saved := saved + 1;
    ELSE
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'already had ingredients');
    END IF;
  END LOOP;
  RETURN jsonb_build_object('saved', saved, 'skipped', skipped);
END;
$$;

-- Same as complete_recipes_batch, in a compact form for writing many recipes:
--   [["<recipe id>", [["basmati rice", 300, "g", "rinsed"], ["salt", null, "to taste"]], ["Step one…", "Step two…"]], …]
CREATE OR REPLACE FUNCTION public.complete_recipes_compact(batch jsonb)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT public.complete_recipes_batch(coalesce(jsonb_agg(jsonb_build_object(
    'id', x ->> 0,
    'items', (SELECT jsonb_agg(jsonb_build_object('name', i ->> 0, 'quantity', i -> 1, 'unit', i ->> 2, 'notes', i ->> 3))
              FROM jsonb_array_elements(x -> 1) i),
    'steps', (SELECT jsonb_agg(jsonb_build_object('instruction', st)) FROM jsonb_array_elements_text(x -> 2) st),
    'allergens', coalesce(x -> 3, '[]')
  )), '[]'))
  FROM jsonb_array_elements(batch) x;
$$;

-- Re-checks every library recipe's ingredients against the allergen rules and
-- adds any missing tags (run after the rules change). Returns tags added.
CREATE OR REPLACE FUNCTION public.retag_recipe_allergens()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE added integer;
BEGIN
  WITH found AS (
    SELECT ri.recipe_id, unnest(public.recipe_allergen_names(array_agg(lower(i.name)))) AS rule
    FROM public.recipe_ingredients ri JOIN public.ingredients i ON i.id = ri.ingredient_id
    GROUP BY ri.recipe_id
  ), aliases(rule, names) AS (VALUES
${aliasRows}
  ), matched AS (
    SELECT DISTINCT f.recipe_id,
      (SELECT a.id FROM public.allergens a WHERE lower(a.name) = ANY (al.names) ORDER BY a.name LIMIT 1) AS allergen_id
    FROM found f JOIN aliases al ON al.rule = f.rule
  ), ins AS (
    INSERT INTO public.recipe_allergens (recipe_id, allergen_id)
    SELECT m.recipe_id, m.allergen_id FROM matched m
    WHERE m.allergen_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.recipe_allergens ra WHERE ra.recipe_id = m.recipe_id AND ra.allergen_id = m.allergen_id)
    RETURNING 1
  )
  SELECT count(*) INTO added FROM ins;
  RETURN added;
END;
$$;

DO $$
DECLARE fn text;
BEGIN
  FOREACH fn IN ARRAY ARRAY['public.complete_recipes_batch(jsonb)', 'public.complete_recipes_compact(jsonb)', 'public.retag_recipe_allergens()'] LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC', fn);
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM anon, authenticated', fn);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', fn);
    END IF;
  END LOOP;
END $$;
`;

writeFileSync(OUT, sql);
console.log(`Wrote ${OUT}`);
