-- GENERATED by supabase/seed/build-recipe-checks.mts from the halal and
-- allergen rules the app uses. Do not edit by hand. Re-runnable.

-- Why a recipe is not halal, or null. Same rules as supabase/functions/_shared/halal.ts.
CREATE OR REPLACE FUNCTION public.recipe_haram_reason(ingredients text[], steps text[])
RETURNS text LANGUAGE plpgsql IMMUTABLE SET search_path = public AS $$
DECLARE
  txt text;
BEGIN
  FOREACH txt IN ARRAY coalesce(ingredients, '{}') LOOP
    IF txt ~* '\y(pork|bacon|ham|lard|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling)\y' THEN
      RETURN substring(txt from '(?i)(\y(pork|bacon|ham|lard|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling)\y)') || ' (' || 'pork' || ')';
    END IF;
    IF txt ~* '\y(?<!beef |chicken |halal )(chorizo|salami|sausages?)\y' THEN
      RETURN substring(txt from '(?i)(\y(?<!beef |chicken |halal )(chorizo|salami|sausages?)\y)') || ' (' || 'possibly pork (say beef/chicken/halal)' || ')';
    END IF;
    IF txt ~* '\y(wine|beer|ale|lager|rum|sake|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|sherry|port|marsala|kirsch|champagne|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|amaretto|kahlua)\y' THEN
      RETURN substring(txt from '(?i)(\y(wine|beer|ale|lager|rum|sake|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|sherry|port|marsala|kirsch|champagne|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|amaretto|kahlua)\y)') || ' (' || 'alcohol' || ')';
    END IF;
    IF txt ~* '\y(?<!halal |beef |fish |agar )(gelatin|gelatine)\y' THEN
      RETURN substring(txt from '(?i)(\y(?<!halal |beef |fish |agar )(gelatin|gelatine)\y)') || ' (' || 'gelatin (say halal gelatin)' || ')';
    END IF;
    IF txt ~* '\yvanilla extract\y' THEN
      RETURN substring(txt from '(?i)(\yvanilla extract\y)') || ' (' || 'vanilla extract contains alcohol (use vanilla powder)' || ')';
    END IF;
    IF txt ~* '\yblood\y' THEN
      RETURN substring(txt from '(?i)(\yblood\y)') || ' (' || 'blood' || ')';
    END IF;
  END LOOP;
  -- Method text: the ingredient-only rules ("sausages") are skipped.
  FOREACH txt IN ARRAY coalesce(steps, '{}') LOOP
    IF txt ~* '\y(pork|bacon|ham|lard|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling)\y' THEN
      RETURN substring(txt from '(?i)(\y(pork|bacon|ham|lard|pancetta|prosciutto|pepperoni|guanciale|gammon|crackling)\y)') || ' (' || 'pork' || ')';
    END IF;
    IF txt ~* '\y(wine|beer|ale|lager|rum|sake|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|sherry|port|marsala|kirsch|champagne|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|amaretto|kahlua)\y' THEN
      RETURN substring(txt from '(?i)(\y(wine|beer|ale|lager|rum|sake|mirin|brandy|cognac|vodka|whisk(e)?y|liqueur|sherry|port|marsala|kirsch|champagne|cider(?! vinegar)|shaoxing|rice wine|cooking wine|bourbon|gin|tequila|amaretto|kahlua)\y)') || ' (' || 'alcohol' || ')';
    END IF;
    IF txt ~* '\y(?<!halal |beef |fish |agar )(gelatin|gelatine)\y' THEN
      RETURN substring(txt from '(?i)(\y(?<!halal |beef |fish |agar )(gelatin|gelatine)\y)') || ' (' || 'gelatin (say halal gelatin)' || ')';
    END IF;
    IF txt ~* '\yvanilla extract\y' THEN
      RETURN substring(txt from '(?i)(\yvanilla extract\y)') || ' (' || 'vanilla extract contains alcohol (use vanilla powder)' || ')';
    END IF;
    IF txt ~* '\yblood\y' THEN
      RETURN substring(txt from '(?i)(\yblood\y)') || ' (' || 'blood' || ')';
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$;

-- Allergen names found in ingredient names. Same rules as supabase/functions/_shared/allergens.ts.
CREATE OR REPLACE FUNCTION public.recipe_allergen_names(ingredients text[])
RETURNS text[] LANGUAGE plpgsql IMMUTABLE SET search_path = public AS $$
DECLARE
  raw text;
  n text;
  found text[] := '{}';
BEGIN
  FOREACH raw IN ARRAY coalesce(ingredients, '{}') LOOP
    n := trim(regexp_replace(regexp_replace(lower(raw), '[’`]', '''', 'g'), '\s+', ' ', 'g'));
      IF regexp_replace(n, '\y(rice flour|glutinous rice flour|gluten-free|chickpea flour|gram flour|besan|corn ?flour|cornmeal|(white |yellow )?maize (flour|meal)|maize|almond flour|coconut flour|tapioca|cassava|teff|potato flour|buckwheat|rice noodles?|rice vermicelli|glass noodles|rice paper|corn tortillas?|tamari|coconut aminos|rice cakes?)\y', ' ', 'g') ~ '\y(flour|bread|breadcrumbs?|brioche|baguettes?|croissants?|bagels?|sourdough|msemen|baghrir|pretzels?|waffles?|crumpets?|muffins?|panko|pitta?s?|naan|chapati|roti|paratha|flatbreads?|lepinja|tortillas?|wraps?|pasta|spaghetti|penne|fusilli|macaroni|fettuccine|tagliatelle|linguine|rigatoni|ravioli|tortellini|buns?|bread rolls?|granola|muesli|lasagne|lasagna|orzo|noodles?|vermicelli|couscous|bulgur|bulgh?ur|freekeh|frik|semolina|barley|wheat|rye|spelt|seitan|filo|phyllo|puff pastry|pastry|brik|warka|pizza dough|dough|soy sauce|kecap manis|teriyaki sauce|oyster sauce|hoisin|crackers?|biscuits?|cake|rusk|kataifi|kunafa|knafeh|malt|jareesh|harees|yufka)\y' THEN found := array_append(found, 'Gluten'); END IF;
      IF regexp_replace(n, '\y(coconut milk|coconut cream|almond milk|oat milk|soy milk|soya milk|rice milk|peanut butter|almond butter|cashew butter|nut butter|shea butter|cocoa butter|cream of tartar|butter beans?|butterhead|dairy-free|vegan (butter|cheese|yogh?urt)|coconut yogh?urt)\y', ' ', 'g') ~ '\y(milk|butter|ghee|cream|yogh?urt|labneh|cheese|paneer|feta|halloumi|mozzarella|parmesan|cheddar|ricotta|mascarpone|akkawi|nabulsi|jameed|kashk|kefir|buttermilk|whey|casein|custard|ice cream|khoa|khoya|condensed|evaporated|tzatziki|creme fraiche|crème fraîche|qishta|ashta)\y' THEN found := array_append(found, 'Dairy'); END IF;
      IF regexp_replace(n, '\y(eggplants?|egg-free|vegan mayo)\y', ' ', 'g') ~ '\y(eggs?|egg yolks?|egg whites?|mayonnaise|mayo|meringue|aioli)\y' THEN found := array_append(found, 'Eggs'); END IF;
      IF regexp_replace(n, '\y(nutmeg|coconut|doughnut|butternut|peanuts?|tiger nuts?|water chestnuts?)\y', ' ', 'g') ~ '\y(almonds?|walnuts?|pistachios?|cashews?|hazelnuts?|pecans?|pine nuts?|macadamias?|brazil nuts?|praline|marzipan|frangipane|nut butter|almond (flour|milk|butter|extract)|mixed nuts|nuts)\y' THEN found := array_append(found, 'Tree nuts'); END IF;
      IF n ~ '\y(peanuts?|groundnuts?|peanut butter|peanut oil|satay sauce)\y' THEN found := array_append(found, 'Peanuts'); END IF;
      IF n ~ '\y(sesame|tahini|tahina|za''?atar|halva|halwa tahini|dukkah|gomasio)\y' THEN found := array_append(found, 'Sesame'); END IF;
      IF regexp_replace(n, '\y(fish-free|vegan fish sauce)\y', ' ', 'g') ~ '\y(fish|salmon|tuna|cod|haddock|hake|pollock|tilapia|sea ?bass|branzino|bream|snapper|mackerel|sardines?|anchov(y|ies)|herring|trout|halibut|kingfish|grouper|carp|catfish|swordfish|whitebait|fish sauce|worcestershire|shito|bonito|dashi|maldive fish|dried fish)\y' THEN found := array_append(found, 'Fish'); END IF;
      IF n ~ '\y(prawns?|shrimps?|crabs?|lobsters?|crayfish|langoustines?|mussels?|clams?|oysters?|scallops?|squid|calamari|octopus|cuttlefish|shrimp paste|belacan|laksa paste|shito|terasi|oyster sauce|dried shrimp)\y' THEN found := array_append(found, 'Shellfish'); END IF;
      IF n ~ '\y(soy|soya|tofu|tempeh|edamame|miso|kecap manis|tamari|teriyaki sauce|soybeans?|hoisin)\y' THEN found := array_append(found, 'Soy'); END IF;
      IF n ~ '\y(mustard)\y' THEN found := array_append(found, 'Mustard'); END IF;
      IF n ~ '\y(celery|celeriac|stock cubes?|bouillon)\y' THEN found := array_append(found, 'Celery'); END IF;
  END LOOP;
  RETURN ARRAY(SELECT DISTINCT unnest(found) ORDER BY 1);
END;
$$;

-- Saves many recipes at once: each one is checked for halal, its allergens are
-- tagged (from the rules plus any listed), then it is saved with complete_recipe.
--   batch: [{ "id": "…", "items": [...], "steps": [...], "allergens": ["Dairy"] }]
-- Returns { "saved": n, "skipped": [{ "id", "reason" }] }.
CREATE OR REPLACE FUNCTION public.complete_recipes_batch(batch jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  r jsonb;
  names text[];
  method text[];
  why text;
  tags text[];
  candidates jsonb;
  saved integer := 0;
  skipped jsonb := '[]';
BEGIN
  FOR r IN SELECT * FROM jsonb_array_elements(batch) LOOP
    names := ARRAY(SELECT lower(x ->> 'name') FROM jsonb_array_elements(r -> 'items') x);
    method := ARRAY(SELECT x ->> 'instruction' FROM jsonb_array_elements(r -> 'steps') x);
    why := public.recipe_haram_reason(names, method);
    IF why IS NOT NULL THEN
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'not halal: ' || why);
      CONTINUE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.recipes WHERE id = (r ->> 'id')::uuid) THEN
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'recipe not found');
      CONTINUE;
    END IF;
    tags := public.recipe_allergen_names(names)
      || ARRAY(SELECT jsonb_array_elements_text(coalesce(r -> 'allergens', '[]')));
    SELECT coalesce(jsonb_agg(to_jsonb(a.names)), '[]') INTO candidates
      FROM (VALUES
    ('Gluten', ARRAY['gluten', 'gluten', 'wheat', 'coeliac', 'celiac', 'barley', 'rye']),
    ('Dairy', ARRAY['dairy', 'dairy', 'milk', 'lactose', 'cow milk']),
    ('Eggs', ARRAY['eggs', 'egg', 'eggs']),
    ('Tree nuts', ARRAY['tree nuts', 'tree nuts', 'tree nut', 'nuts', 'nut']),
    ('Peanuts', ARRAY['peanuts', 'peanut', 'peanuts', 'groundnut', 'groundnuts']),
    ('Sesame', ARRAY['sesame', 'sesame']),
    ('Fish', ARRAY['fish', 'fish']),
    ('Shellfish', ARRAY['shellfish', 'shellfish', 'crustaceans', 'molluscs', 'mollusks', 'seafood']),
    ('Soy', ARRAY['soy', 'soy', 'soya', 'soybean', 'soybeans']),
    ('Mustard', ARRAY['mustard', 'mustard']),
    ('Celery', ARRAY['celery', 'celery', 'celeriac'])
      ) AS a(rule, names)
      WHERE lower(a.rule) IN (SELECT lower(t) FROM unnest(tags) t);
    IF public.complete_recipe((r ->> 'id')::uuid, r -> 'items', r -> 'steps', candidates) > 0 THEN
      saved := saved + 1;
    ELSE
      skipped := skipped || jsonb_build_object('id', r ->> 'id', 'reason', 'already had ingredients');
    END IF;
  END LOOP;
  RETURN jsonb_build_object('saved', saved, 'skipped', skipped);
END;
$$;

-- Same as complete_recipes_batch, in a compact form for writing many recipes:
--   [["<recipe id>", [["basmati rice", 300, "g", "rinsed"], ["salt", null, "to taste"]], ["Step one…", "Step two…"]], …]
CREATE OR REPLACE FUNCTION public.complete_recipes_compact(batch jsonb)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT public.complete_recipes_batch(coalesce(jsonb_agg(jsonb_build_object(
    'id', x ->> 0,
    'items', (SELECT jsonb_agg(jsonb_build_object('name', i ->> 0, 'quantity', i -> 1, 'unit', i ->> 2, 'notes', i ->> 3))
              FROM jsonb_array_elements(x -> 1) i),
    'steps', (SELECT jsonb_agg(jsonb_build_object('instruction', st)) FROM jsonb_array_elements_text(x -> 2) st),
    'allergens', coalesce(x -> 3, '[]')
  )), '[]'))
  FROM jsonb_array_elements(batch) x;
$$;

-- Re-checks every library recipe's ingredients against the allergen rules and
-- adds any missing tags (run after the rules change). Returns tags added.
CREATE OR REPLACE FUNCTION public.retag_recipe_allergens()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE added integer;
BEGIN
  WITH found AS (
    SELECT ri.recipe_id, unnest(public.recipe_allergen_names(array_agg(lower(i.name)))) AS rule
    FROM public.recipe_ingredients ri JOIN public.ingredients i ON i.id = ri.ingredient_id
    GROUP BY ri.recipe_id
  ), aliases(rule, names) AS (VALUES
    ('Gluten', ARRAY['gluten', 'gluten', 'wheat', 'coeliac', 'celiac', 'barley', 'rye']),
    ('Dairy', ARRAY['dairy', 'dairy', 'milk', 'lactose', 'cow milk']),
    ('Eggs', ARRAY['eggs', 'egg', 'eggs']),
    ('Tree nuts', ARRAY['tree nuts', 'tree nuts', 'tree nut', 'nuts', 'nut']),
    ('Peanuts', ARRAY['peanuts', 'peanut', 'peanuts', 'groundnut', 'groundnuts']),
    ('Sesame', ARRAY['sesame', 'sesame']),
    ('Fish', ARRAY['fish', 'fish']),
    ('Shellfish', ARRAY['shellfish', 'shellfish', 'crustaceans', 'molluscs', 'mollusks', 'seafood']),
    ('Soy', ARRAY['soy', 'soy', 'soya', 'soybean', 'soybeans']),
    ('Mustard', ARRAY['mustard', 'mustard']),
    ('Celery', ARRAY['celery', 'celery', 'celeriac'])
  ), matched AS (
    SELECT DISTINCT f.recipe_id,
      (SELECT a.id FROM public.allergens a WHERE lower(a.name) = ANY (al.names) ORDER BY a.name LIMIT 1) AS allergen_id
    FROM found f JOIN aliases al ON al.rule = f.rule
  ), ins AS (
    INSERT INTO public.recipe_allergens (recipe_id, allergen_id)
    SELECT m.recipe_id, m.allergen_id FROM matched m
    WHERE m.allergen_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM public.recipe_allergens ra WHERE ra.recipe_id = m.recipe_id AND ra.allergen_id = m.allergen_id)
    RETURNING 1
  )
  SELECT count(*) INTO added FROM ins;
  RETURN added;
END;
$$;

DO $$
DECLARE fn text;
BEGIN
  FOREACH fn IN ARRAY ARRAY['public.complete_recipes_batch(jsonb)', 'public.complete_recipes_compact(jsonb)', 'public.retag_recipe_allergens()'] LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC', fn);
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM anon, authenticated', fn);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
      EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', fn);
    END IF;
  END LOOP;
END $$;
